/* Frecuencia — Spanish youth/colloquial slang (mostly Spain).
   Appears as a reward in the card deck after ~300 learned words. All marked "(Slang)".
   SLANG rows: [es, de, pos]. SLANG_VERBS rows: [inf, de, reg, grp] (also added to Verben tab). */
window.SLANG = [
  ["guay","cool / super","Adj (Slang)"],
  ["chulo","cool / frech","Adj (Slang)"],
  ["majo","nett / sympathisch","Adj (Slang)"],
  ["chungo","mies / übel / schwierig","Adj (Slang)"],
  ["cutre","schäbig / billig","Adj (Slang)"],
  ["chachi","klasse / prima","Adj (Slang)"],
  ["flipante","der Wahnsinn / irre","Adj (Slang)"],
  ["molón","klasse / geil","Adj (Slang)"],
  ["pijo","versnobt / schnöselig","Adj (Slang)"],
  ["random","random / zufällig / beliebig","Adj (Slang)"],
  ["friki","Freak / Nerd","S (Slang)"],
  ["crack","Ass / Könner","S (Slang)"],
  ["tío","Typ / Alter / Kumpel","S (Slang)"],
  ["tía","Alte / Kumpeline","S (Slang)"],
  ["chaval","Junge / Kerl","S (Slang)"],
  ["colega","Kumpel","S (Slang)"],
  ["pana","Kumpel (Latam)","S (Slang)"],
  ["birra","Bier","S (Slang)"],
  ["pasta","Kohle / Geld","S (Slang)"],
  ["curro","Job / Arbeit","S (Slang)"],
  ["movida","Sache / Ärger / Ding","S (Slang)"],
  ["follón","Chaos / Krach","S (Slang)"],
  ["garito","Schuppen / Bar / Laden","S (Slang)"],
  ["resaca","Kater (nach Party)","S (Slang)"],
  ["ligue","Flirt / Eroberung","S (Slang)"],
  ["crush","Schwarm","S (Slang)"],
  ["guiri","Ausländer / Tourist","S (Slang)"],
  ["cotilla","Klatschtante / neugierig","S (Slang)"],
  ["petardo","Nervensäge / Langweiler","S (Slang)"],
  ["finde","Wochenende","S (Slang)"],
  ["postureo","Selbstinszenierung / Fassade","S (Slang)"],
  ["salseo","Drama / Klatsch","S (Slang)"],
  ["zasca","Konter / Seitenhieb","S (Slang)"],
  ["mogollón","jede Menge / massig","Adv (Slang)"],
  ["porfa","bitte (kurz)","Interj (Slang)"],
  ["genial","genial / super","Adj (Slang)"]
];
window.SLANG_VERBS = [
  ["molar","gefallen / cool sein",true,"ar"],
  ["flipar","ausflippen / staunen",true,"ar"],
  ["currar","schuften / arbeiten",true,"ar"],
  ["fardar","angeben / protzen",true,"ar"],
  ["petar","abgehen / vollpacken",true,"ar"],
  ["cotillear","tratschen",true,"ar"],
  ["pillar","kapieren / schnappen",true,"ar"],
  ["rayarse","sich verrückt machen / grübeln",true,"ar"],
  ["pirarse","abhauen",true,"ar"],
  ["enrollarse","labern / sich einlassen",true,"ar"],
  ["liarse","sich verzetteln / durcheinanderkommen",true,"ar"],
  ["espabilar","aufwachen / sich sputen",true,"ar"],
  ["ligar","flirten / anbaggern",true,"ar"]
];
