/* Frecuencia — verb data for the "Verben" tab.
   Persons order everywhere: yo, tú, él/ella, nosotros, vosotros, ellos/ellas.
   VERBCONJ: hand-checked tables for key irregular verbs (pres/pret[indefinido]/fut).
   VERBLIST: infinitives + German meaning (+ reg flag for the regular engine). */

window.VERB_PERSONS = [
  ["yo","ich"],["tú","du"],["él/ella","er/sie"],
  ["nosotros","wir"],["vosotros","ihr"],["ellos/ellas","sie"]
];

// Pretérito perfecto = haber (present) + participio.
window.HABER_PRES = ["he","has","ha","hemos","habéis","han"];
// Presente continuo = estar (present) + gerundio. Irregular gerundios (regular = -ando / -iendo):
window.GER = {
  "ir":"yendo","poder":"pudiendo","decir":"diciendo","venir":"viniendo","traer":"trayendo",
  "dormir":"durmiendo","pedir":"pidiendo","sentir":"sintiendo","seguir":"siguiendo","leer":"leyendo",
  "oír":"oyendo","caer":"cayendo","morir":"muriendo","construir":"construyendo","reír":"riendo",
  "repetir":"repitiendo","servir":"sirviendo","preferir":"prefiriendo","mentir":"mintiendo",
  "elegir":"eligiendo","conseguir":"consiguiendo","corregir":"corrigiendo"
};
// Irregular past participles (regular = -ado / -ido, handled by rule).
window.PART = {
  "escribir":"escrito", "abrir":"abierto", "hacer":"hecho", "decir":"dicho",
  "ver":"visto", "poner":"puesto", "volver":"vuelto", "traer":"traído",
  "leer":"leído", "romper":"roto", "morir":"muerto", "descubrir":"descubierto"
};

window.VERBCONJ = {
  "ser":     { pres:["soy","eres","es","somos","sois","son"], pret:["fui","fuiste","fue","fuimos","fuisteis","fueron"], fut:["seré","serás","será","seremos","seréis","serán"], imp:["era","eras","era","éramos","erais","eran"] },
  "estar":   { pres:["estoy","estás","está","estamos","estáis","están"], pret:["estuve","estuviste","estuvo","estuvimos","estuvisteis","estuvieron"], fut:["estaré","estarás","estará","estaremos","estaréis","estarán"] },
  "tener":   { pres:["tengo","tienes","tiene","tenemos","tenéis","tienen"], pret:["tuve","tuviste","tuvo","tuvimos","tuvisteis","tuvieron"], fut:["tendré","tendrás","tendrá","tendremos","tendréis","tendrán"] },
  "ir":      { pres:["voy","vas","va","vamos","vais","van"], pret:["fui","fuiste","fue","fuimos","fuisteis","fueron"], fut:["iré","irás","irá","iremos","iréis","irán"], imp:["iba","ibas","iba","íbamos","ibais","iban"] },
  "hacer":   { pres:["hago","haces","hace","hacemos","hacéis","hacen"], pret:["hice","hiciste","hizo","hicimos","hicisteis","hicieron"], fut:["haré","harás","hará","haremos","haréis","harán"] },
  "poder":   { pres:["puedo","puedes","puede","podemos","podéis","pueden"], pret:["pude","pudiste","pudo","pudimos","pudisteis","pudieron"], fut:["podré","podrás","podrá","podremos","podréis","podrán"] },
  "querer":  { pres:["quiero","quieres","quiere","queremos","queréis","quieren"], pret:["quise","quisiste","quiso","quisimos","quisisteis","quisieron"], fut:["querré","querrás","querrá","querremos","querréis","querrán"] },
  "decir":   { pres:["digo","dices","dice","decimos","decís","dicen"], pret:["dije","dijiste","dijo","dijimos","dijisteis","dijeron"], fut:["diré","dirás","dirá","diremos","diréis","dirán"] },
  "ver":     { pres:["veo","ves","ve","vemos","veis","ven"], pret:["vi","viste","vio","vimos","visteis","vieron"], fut:["veré","verás","verá","veremos","veréis","verán"], imp:["veía","veías","veía","veíamos","veíais","veían"] },
  "dar":     { pres:["doy","das","da","damos","dais","dan"], pret:["di","diste","dio","dimos","disteis","dieron"], fut:["daré","darás","dará","daremos","daréis","darán"] },
  "saber":   { pres:["sé","sabes","sabe","sabemos","sabéis","saben"], pret:["supe","supiste","supo","supimos","supisteis","supieron"], fut:["sabré","sabrás","sabrá","sabremos","sabréis","sabrán"] },
  "poner":   { pres:["pongo","pones","pone","ponemos","ponéis","ponen"], pret:["puse","pusiste","puso","pusimos","pusisteis","pusieron"], fut:["pondré","pondrás","pondrá","pondremos","pondréis","pondrán"] },
  "venir":   { pres:["vengo","vienes","viene","venimos","venís","vienen"], pret:["vine","viniste","vino","vinimos","vinisteis","vinieron"], fut:["vendré","vendrás","vendrá","vendremos","vendréis","vendrán"] },
  "salir":   { pres:["salgo","sales","sale","salimos","salís","salen"], pret:["salí","saliste","salió","salimos","salisteis","salieron"], fut:["saldré","saldrás","saldrá","saldremos","saldréis","saldrán"] },
  "traer":   { pres:["traigo","traes","trae","traemos","traéis","traen"], pret:["traje","trajiste","trajo","trajimos","trajisteis","trajeron"], fut:["traeré","traerás","traerá","traeremos","traeréis","traerán"] },
  "conocer": { pres:["conozco","conoces","conoce","conocemos","conocéis","conocen"], pret:["conocí","conociste","conoció","conocimos","conocisteis","conocieron"], fut:["conoceré","conocerás","conocerá","conoceremos","conoceréis","conocerán"] },
  "pensar":  { pres:["pienso","piensas","piensa","pensamos","pensáis","piensan"], pret:["pensé","pensaste","pensó","pensamos","pensasteis","pensaron"], fut:["pensaré","pensarás","pensará","pensaremos","pensaréis","pensarán"] },
  "volver":  { pres:["vuelvo","vuelves","vuelve","volvemos","volvéis","vuelven"], pret:["volví","volviste","volvió","volvimos","volvisteis","volvieron"], fut:["volveré","volverás","volverá","volveremos","volveréis","volverán"] },
  "dormir":  { pres:["duermo","duermes","duerme","dormimos","dormís","duermen"], pret:["dormí","dormiste","durmió","dormimos","dormisteis","durmieron"], fut:["dormiré","dormirás","dormirá","dormiremos","dormiréis","dormirán"] },
  "pedir":   { pres:["pido","pides","pide","pedimos","pedís","piden"], pret:["pedí","pediste","pidió","pedimos","pedisteis","pidieron"], fut:["pediré","pedirás","pedirá","pediremos","pediréis","pedirán"] },
  "jugar":   { pres:["juego","juegas","juega","jugamos","jugáis","juegan"], pret:["jugué","jugaste","jugó","jugamos","jugasteis","jugaron"], fut:["jugaré","jugarás","jugará","jugaremos","jugaréis","jugarán"] },
  "empezar": { pres:["empiezo","empiezas","empieza","empezamos","empezáis","empiezan"], pret:["empecé","empezaste","empezó","empezamos","empezasteis","empezaron"], fut:["empezaré","empezarás","empezará","empezaremos","empezaréis","empezarán"] },
  "sentir":  { pres:["siento","sientes","siente","sentimos","sentís","sienten"], pret:["sentí","sentiste","sintió","sentimos","sentisteis","sintieron"], fut:["sentiré","sentirás","sentirá","sentiremos","sentiréis","sentirán"] },
  "seguir":  { pres:["sigo","sigues","sigue","seguimos","seguís","siguen"], pret:["seguí","seguiste","siguió","seguimos","seguisteis","siguieron"], fut:["seguiré","seguirás","seguirá","seguiremos","seguiréis","seguirán"] },
  "conducir":{ pres:["conduzco","conduces","conduce","conducimos","conducís","conducen"], pret:["conduje","condujiste","condujo","condujimos","condujisteis","condujeron"], fut:["conduciré","conducirás","conducirá","conduciremos","conduciréis","conducirán"] },
  "leer":    { pres:["leo","lees","lee","leemos","leéis","leen"], pret:["leí","leíste","leyó","leímos","leísteis","leyeron"], fut:["leeré","leerás","leerá","leeremos","leeréis","leerán"] },
  "cerrar":  { pres:["cierro","cierras","cierra","cerramos","cerráis","cierran"], pret:["cerré","cerraste","cerró","cerramos","cerrasteis","cerraron"], fut:["cerraré","cerrarás","cerrará","cerraremos","cerraréis","cerrarán"] },
  "perder":  { pres:["pierdo","pierdes","pierde","perdemos","perdéis","pierden"], pret:["perdí","perdiste","perdió","perdimos","perdisteis","perdieron"], fut:["perderé","perderás","perderá","perderemos","perderéis","perderán"] },
  "entender":{ pres:["entiendo","entiendes","entiende","entendemos","entendéis","entienden"], pret:["entendí","entendiste","entendió","entendimos","entendisteis","entendieron"], fut:["entenderé","entenderás","entenderá","entenderemos","entenderéis","entenderán"] },
  "encontrar":{ pres:["encuentro","encuentras","encuentra","encontramos","encontráis","encuentran"], pret:["encontré","encontraste","encontró","encontramos","encontrasteis","encontraron"], fut:["encontraré","encontrarás","encontrará","encontraremos","encontraréis","encontrarán"] },
  "contar":  { pres:["cuento","cuentas","cuenta","contamos","contáis","cuentan"], pret:["conté","contaste","contó","contamos","contasteis","contaron"], fut:["contaré","contarás","contará","contaremos","contaréis","contarán"] },
  "recordar":{ pres:["recuerdo","recuerdas","recuerda","recordamos","recordáis","recuerdan"], pret:["recordé","recordaste","recordó","recordamos","recordasteis","recordaron"], fut:["recordaré","recordarás","recordará","recordaremos","recordaréis","recordarán"] },
  "costar":  { pres:["cuesto","cuestas","cuesta","costamos","costáis","cuestan"], pret:["costé","costaste","costó","costamos","costasteis","costaron"], fut:["costaré","costarás","costará","costaremos","costaréis","costarán"] },
  "probar":  { pres:["pruebo","pruebas","prueba","probamos","probáis","prueban"], pret:["probé","probaste","probó","probamos","probasteis","probaron"], fut:["probaré","probarás","probará","probaremos","probaréis","probarán"] },
  "mostrar": { pres:["muestro","muestras","muestra","mostramos","mostráis","muestran"], pret:["mostré","mostraste","mostró","mostramos","mostrasteis","mostraron"], fut:["mostraré","mostrarás","mostrará","mostraremos","mostraréis","mostrarán"] },
  "mover":   { pres:["muevo","mueves","mueve","movemos","movéis","mueven"], pret:["moví","moviste","movió","movimos","movisteis","movieron"], fut:["moveré","moverás","moverá","moveremos","moveréis","moverán"] },
  "oler":    { pres:["huelo","hueles","huele","olemos","oléis","huelen"], pret:["olí","oliste","olió","olimos","olisteis","olieron"], fut:["oleré","olerás","olerá","oleremos","oleréis","olerán"] },
  "oír":     { pres:["oigo","oyes","oye","oímos","oís","oyen"], pret:["oí","oíste","oyó","oímos","oísteis","oyeron"], fut:["oiré","oirás","oirá","oiremos","oiréis","oirán"] },
  "caer":    { pres:["caigo","caes","cae","caemos","caéis","caen"], pret:["caí","caíste","cayó","caímos","caísteis","cayeron"], fut:["caeré","caerás","caerá","caeremos","caeréis","caerán"] },
  "servir":  { pres:["sirvo","sirves","sirve","servimos","servís","sirven"], pret:["serví","serviste","sirvió","servimos","servisteis","sirvieron"], fut:["serviré","servirás","servirá","serviremos","serviréis","servirán"] },
  "repetir": { pres:["repito","repites","repite","repetimos","repetís","repiten"], pret:["repetí","repetiste","repitió","repetimos","repetisteis","repitieron"], fut:["repetiré","repetirás","repetirá","repetiremos","repetiréis","repetirán"] },
  "reír":    { pres:["río","ríes","ríe","reímos","reís","ríen"], pret:["reí","reíste","rió","reímos","reísteis","rieron"], fut:["reiré","reirás","reirá","reiremos","reiréis","reirán"] },
  "morir":   { pres:["muero","mueres","muere","morimos","morís","mueren"], pret:["morí","moriste","murió","morimos","moristeis","murieron"], fut:["moriré","morirás","morirá","moriremos","moriréis","morirán"] },
  "construir":{ pres:["construyo","construyes","construye","construimos","construís","construyen"], pret:["construí","construiste","construyó","construimos","construisteis","construyeron"], fut:["construiré","construirás","construirá","construiremos","construiréis","construirán"] }
};

// Infinitives + German meaning. reg:true => fully regular (engine conjugates).
// grp = ar|er|ir. Verbs present in VERBCONJ are the "irregular" set for drills.
window.VERBLIST = [
  // --- key irregular / stem-changing (have tables where drillable) ---
  ["ser","sein",false,"er"],["estar","sein (Zustand/Ort)",false,"ar"],["tener","haben",false,"er"],
  ["ir","gehen",false,"ir"],["hacer","machen/tun",false,"er"],["poder","können",false,"er"],
  ["querer","wollen/lieben",false,"er"],["decir","sagen",false,"ir"],["ver","sehen",false,"er"],
  ["dar","geben",false,"ar"],["saber","wissen",false,"er"],["poner","stellen/legen",false,"er"],
  ["venir","kommen",false,"ir"],["salir","hinausgehen",false,"ir"],["traer","bringen",false,"er"],
  ["conocer","kennen(lernen)",false,"er"],["pensar","denken",false,"ar"],["volver","zurückkehren",false,"er"],
  ["dormir","schlafen",false,"ir"],["pedir","bitten/bestellen",false,"ir"],["jugar","spielen",false,"ar"],
  ["empezar","anfangen",false,"ar"],["sentir","fühlen",false,"ir"],["seguir","folgen/weitermachen",false,"ir"],
  ["conducir","fahren (lenken)",false,"ir"],["leer","lesen",false,"er"],
  // --- fully regular (engine) ---
  ["hablar","sprechen",true,"ar"],["trabajar","arbeiten",true,"ar"],["estudiar","lernen/studieren",true,"ar"],
  ["comprar","kaufen",true,"ar"],["tomar","nehmen",true,"ar"],["mirar","schauen",true,"ar"],
  ["escuchar","zuhören",true,"ar"],["esperar","warten/hoffen",true,"ar"],["ayudar","helfen",true,"ar"],
  ["necesitar","brauchen",true,"ar"],["usar","benutzen",true,"ar"],["cantar","singen",true,"ar"],
  ["bailar","tanzen",true,"ar"],["cocinar","kochen",true,"ar"],["preguntar","fragen",true,"ar"],
  ["contestar","antworten",true,"ar"],["viajar","reisen",true,"ar"],["descansar","sich ausruhen",true,"ar"],
  ["terminar","beenden",true,"ar"],["entrar","hineingehen",true,"ar"],["llevar","tragen/mitnehmen",true,"ar"],
  ["dejar","lassen",true,"ar"],["pasar","vorbeigehen/passieren",true,"ar"],["quedar","bleiben/verabreden",true,"ar"],
  ["mandar","schicken/befehlen",true,"ar"],["visitar","besuchen",true,"ar"],["invitar","einladen",true,"ar"],
  ["preparar","vorbereiten",true,"ar"],["desear","wünschen",true,"ar"],["cambiar","ändern/wechseln",true,"ar"],
  ["ganar","gewinnen/verdienen",true,"ar"],["llamar","rufen/anrufen",true,"ar"],["lavar","waschen",true,"ar"],
  ["caminar","gehen/spazieren",true,"ar"],["nadar","schwimmen",true,"ar"],["saltar","springen",true,"ar"],
  ["arreglar","reparieren/regeln",true,"ar"],["pintar","malen/streichen",true,"ar"],["comer","essen",true,"er"],
  ["beber","trinken",true,"er"],["aprender","lernen",true,"er"],["correr","rennen/laufen",true,"er"],
  ["vender","verkaufen",true,"er"],["comprender","verstehen",true,"er"],["deber","müssen/sollen",true,"er"],
  ["temer","fürchten",true,"er"],["vivir","leben/wohnen",true,"ir"],["escribir","schreiben",true,"ir"],
  ["recibir","erhalten",true,"ir"],["decidir","entscheiden",true,"ir"],["subir","hochgehen/steigen",true,"ir"],
  ["permitir","erlauben",true,"ir"],["existir","existieren",true,"ir"],["abrir","öffnen",true,"ir"],
  // --- more common verbs (infinitive learning; not drilled for conjugation) ---
  ["gustar","gefallen/mögen",false,"ar"],["encantar","begeistern",false,"ar"],["importar","wichtig sein",false,"ar"],
  ["parecer","scheinen",false,"er"],["creer","glauben",false,"er"],["entender","verstehen",false,"er"],
  ["perder","verlieren",false,"er"],["encontrar","finden",false,"ar"],["recordar","sich erinnern",false,"ar"],
  ["contar","zählen/erzählen",false,"ar"],["mostrar","zeigen",false,"ar"],["costar","kosten",false,"ar"],
  ["probar","probieren",false,"ar"],["cerrar","schließen",false,"ar"],["sentarse","sich setzen",false,"ar"],
  ["despertarse","aufwachen",false,"ar"],["acostarse","sich hinlegen",false,"ar"],["vestirse","sich anziehen",false,"ir"],
  ["ducharse","duschen",true,"ar"],["levantarse","aufstehen",true,"ar"],["llamarse","heißen",true,"ar"],
  ["quedarse","bleiben",true,"ar"],["irse","weggehen",false,"ir"],["sentirse","sich fühlen",false,"ir"],
  ["morir","sterben",false,"ir"],["nacer","geboren werden",false,"er"],["crecer","wachsen",false,"er"],
  ["ofrecer","anbieten",false,"er"],["reconocer","erkennen",false,"er"],["producir","produzieren",false,"ir"],
  ["traducir","übersetzen",false,"ir"],["construir","bauen",false,"ir"],["destruir","zerstören",false,"ir"],
  ["oír","hören",false,"ir"],["caer","fallen",false,"er"],["reír","lachen",false,"ir"],
  ["elegir","wählen",false,"ir"],["repetir","wiederholen",false,"ir"],["servir","dienen/servieren",false,"ir"],
  ["mentir","lügen",false,"ir"],["preferir","bevorzugen",false,"ir"],["divertirse","sich amüsieren",false,"ir"],
  ["convertir","verwandeln",false,"ir"],["conseguir","erreichen/bekommen",false,"ir"],["corregir","korrigieren",false,"ir"],
  ["mover","bewegen",false,"er"],["llover","regnen",false,"er"],["soler","pflegen zu",false,"er"],
  ["doler","wehtun",false,"er"],["oler","riechen",false,"er"],["contener","enthalten",false,"er"],
  ["mantener","behalten/halten",false,"er"],["obtener","erhalten/bekommen",false,"er"],["proponer","vorschlagen",false,"er"],
  ["suponer","annehmen",false,"er"],["componer","zusammensetzen",false,"er"],["deshacer","auflösen",false,"er"],
  ["aparecer","erscheinen",false,"er"],["desaparecer","verschwinden",false,"er"],["ofrecerse","sich anbieten",false,"er"],
  ["comenzar","beginnen",false,"ar"],["almorzar","zu Mittag essen",false,"ar"],["mostrarse","sich zeigen",false,"ar"],
  ["encender","anmachen/anzünden",false,"er"],["defender","verteidigen",false,"er"],["extender","ausdehnen",false,"er"],
  ["llegar","ankommen",false,"ar"],["pagar","bezahlen",false,"ar"],["jugarse","riskieren",false,"ar"],
  ["buscar","suchen",false,"ar"],["sacar","herausnehmen",false,"ar"],["tocar","berühren/spielen",false,"ar"],
  ["explicar","erklären",false,"ar"],["practicar","üben",false,"ar"],["organizar","organisieren",false,"ar"],
  ["utilizar","benutzen",false,"ar"],["realizar","durchführen",false,"ar"],["cruzar","überqueren",false,"ar"],
  // --- expansion: more regular -ar (engine-drillable) ---
  ["aceptar","akzeptieren",true,"ar"],["acabar","beenden/aufbrauchen",true,"ar"],["acompañar","begleiten",true,"ar"],
  ["aconsejar","raten",true,"ar"],["adivinar","erraten",true,"ar"],["admirar","bewundern",true,"ar"],
  ["afeitarse","sich rasieren",true,"ar"],["agarrar","packen/greifen",true,"ar"],["alquilar","mieten",true,"ar"],
  ["amar","lieben",true,"ar"],["anotar","notieren",true,"ar"],["anunciar","ankündigen",true,"ar"],
  ["apoyar","unterstützen",true,"ar"],["apreciar","schätzen",true,"ar"],["aprovechar","nutzen",true,"ar"],
  ["apuntar","aufschreiben/zielen",true,"ar"],["asegurar","versichern",true,"ar"],["aumentar","erhöhen",true,"ar"],
  ["avisar","benachrichtigen",true,"ar"],["bajar","heruntergehen",true,"ar"],["bastar","genügen",true,"ar"],
  ["besar","küssen",true,"ar"],["borrar","löschen",true,"ar"],["brillar","glänzen",true,"ar"],
  ["bromear","scherzen",true,"ar"],["calcular","berechnen",true,"ar"],["callar","schweigen",true,"ar"],
  ["calmar","beruhigen",true,"ar"],["cansarse","müde werden",true,"ar"],["casarse","heiraten",true,"ar"],
  ["causar","verursachen",true,"ar"],["celebrar","feiern",true,"ar"],["cenar","zu Abend essen",true,"ar"],
  ["charlar","plaudern",true,"ar"],["cobrar","kassieren",true,"ar"],["colaborar","mitarbeiten",true,"ar"],
  ["comentar","kommentieren",true,"ar"],["comparar","vergleichen",true,"ar"],["comportarse","sich benehmen",true,"ar"],
  ["concentrarse","sich konzentrieren",true,"ar"],["confirmar","bestätigen",true,"ar"],["conservar","bewahren",true,"ar"],
  ["considerar","erwägen",true,"ar"],["consultar","nachschlagen",true,"ar"],["contratar","einstellen",true,"ar"],
  ["controlar","kontrollieren",true,"ar"],["conversar","sich unterhalten",true,"ar"],["crear","schaffen",true,"ar"],
  ["cuidar","pflegen",true,"ar"],["curar","heilen",true,"ar"],["dañar","schaden",true,"ar"],
  ["decorar","dekorieren",true,"ar"],["desayunar","frühstücken",true,"ar"],["disculparse","sich entschuldigen",true,"ar"],
  ["diseñar","entwerfen",true,"ar"],["disfrutar","genießen",true,"ar"],["disparar","schießen",true,"ar"],
  ["doblar","falten/abbiegen",true,"ar"],["dudar","zweifeln",true,"ar"],["durar","dauern",true,"ar"],
  ["echar","werfen/gießen",true,"ar"],["emplear","anstellen/verwenden",true,"ar"],["enamorarse","sich verlieben",true,"ar"],
  ["enfadarse","sich ärgern",true,"ar"],["engañar","täuschen",true,"ar"],["enojarse","sich ärgern",true,"ar"],
  ["enseñar","lehren/zeigen",true,"ar"],["entrenar","trainieren",true,"ar"],["escapar","entkommen",true,"ar"],
  ["evitar","vermeiden",true,"ar"],["examinar","prüfen",true,"ar"],["expresar","ausdrücken",true,"ar"],
  ["faltar","fehlen",true,"ar"],["felicitar","gratulieren",true,"ar"],["fijarse","bemerken/aufpassen",true,"ar"],
  ["firmar","unterschreiben",true,"ar"],["formar","bilden",true,"ar"],["fumar","rauchen",true,"ar"],
  ["funcionar","funktionieren",true,"ar"],["generar","erzeugen",true,"ar"],["golpear","schlagen",true,"ar"],
  ["grabar","aufnehmen",true,"ar"],["gritar","schreien",true,"ar"],["guardar","aufbewahren",true,"ar"],
  ["hallar","finden",true,"ar"],["heredar","erben",true,"ar"],["imaginar","sich vorstellen",true,"ar"],
  ["informar","informieren",true,"ar"],["iniciar","beginnen",true,"ar"],["instalar","installieren",true,"ar"],
  ["intentar","versuchen",true,"ar"],["interesar","interessieren",true,"ar"],["inventar","erfinden",true,"ar"],
  ["jurar","schwören",true,"ar"],["lamentar","bedauern",true,"ar"],["limpiar","putzen",true,"ar"],
  ["luchar","kämpfen",true,"ar"],["manejar","handhaben/fahren",true,"ar"],["matar","töten",true,"ar"],
  ["mejorar","verbessern",true,"ar"],["mencionar","erwähnen",true,"ar"],["mezclar","mischen",true,"ar"],
  ["molestar","stören",true,"ar"],["montar","aufsteigen/montieren",true,"ar"],["mudarse","umziehen",true,"ar"],
  ["notar","bemerken",true,"ar"],["observar","beobachten",true,"ar"],["ocupar","besetzen",true,"ar"],
  ["odiar","hassen",true,"ar"],["olvidar","vergessen",true,"ar"],["opinar","meinen",true,"ar"],
  ["ordenar","ordnen/befehlen",true,"ar"],["parar","anhalten",true,"ar"],["participar","teilnehmen",true,"ar"],
  ["pasear","spazieren",true,"ar"],["pelear","streiten",true,"ar"],["perdonar","verzeihen",true,"ar"],
  ["planchar","bügeln",true,"ar"],["planear","planen",true,"ar"],["plantar","pflanzen",true,"ar"],
  ["portarse","sich benehmen",true,"ar"],["preocuparse","sich sorgen",true,"ar"],["presentar","vorstellen",true,"ar"],
  ["prestar","leihen",true,"ar"],["pronunciar","aussprechen",true,"ar"],["protestar","protestieren",true,"ar"],
  ["quejarse","sich beschweren",true,"ar"],["quemar","verbrennen",true,"ar"],["regalar","schenken",true,"ar"],
  ["regresar","zurückkehren",true,"ar"],["relacionar","in Beziehung setzen",true,"ar"],["rellenar","ausfüllen",true,"ar"],
  ["renunciar","verzichten/kündigen",true,"ar"],["reparar","reparieren",true,"ar"],["reservar","reservieren",true,"ar"],
  ["respetar","respektieren",true,"ar"],["respirar","atmen",true,"ar"],["resultar","sich ergeben",true,"ar"],
  ["retirar","zurückziehen",true,"ar"],["revisar","überprüfen",true,"ar"],["robar","stehlen",true,"ar"],
  ["rodear","umgeben",true,"ar"],["saludar","grüßen",true,"ar"],["salvar","retten",true,"ar"],
  ["señalar","zeigen/hinweisen",true,"ar"],["separar","trennen",true,"ar"],["soportar","ertragen",true,"ar"],
  ["sospechar","verdächtigen",true,"ar"],["subrayar","unterstreichen",true,"ar"],["sumar","addieren",true,"ar"],
  ["superar","überwinden",true,"ar"],["tardar","dauern/brauchen",true,"ar"],["telefonear","telefonieren",true,"ar"],
  ["tirar","werfen/ziehen",true,"ar"],["tolerar","tolerieren",true,"ar"],["trasladar","verlegen",true,"ar"],
  ["tratar","behandeln/versuchen",true,"ar"],["triunfar","triumphieren",true,"ar"],["vigilar","bewachen",true,"ar"],
  ["votar","wählen/abstimmen",true,"ar"],
  // --- expansion: more regular -er / -ir (engine-drillable) ---
  ["meter","hineinstecken",true,"er"],["prometer","versprechen",true,"er"],["responder","antworten",true,"er"],
  ["romper","zerbrechen",true,"er"],["sorprender","überraschen",true,"er"],["suceder","geschehen",true,"er"],
  ["suspender","aussetzen/durchfallen",true,"er"],["toser","husten",true,"er"],["prender","anmachen",true,"er"],
  ["esconder","verstecken",true,"er"],["depender","abhängen",true,"er"],["pretender","beabsichtigen",true,"er"],
  ["recorrer","durchqueren",true,"er"],
  ["compartir","teilen",true,"ir"],["confundir","verwechseln",true,"ir"],["consumir","verbrauchen",true,"ir"],
  ["convivir","zusammenleben",true,"ir"],["cumplir","erfüllen",true,"ir"],["describir","beschreiben",true,"ir"],
  ["descubrir","entdecken",true,"ir"],["imprimir","drucken",true,"ir"],["insistir","bestehen auf",true,"ir"],
  ["interrumpir","unterbrechen",true,"ir"],["partir","abfahren/teilen",true,"ir"],["percibir","wahrnehmen",true,"ir"],
  ["repartir","verteilen",true,"ir"],["sufrir","leiden",true,"ir"],["unir","vereinen",true,"ir"],
  ["asistir","beiwohnen",true,"ir"],
  // --- expansion: irregular / stem-change / spelling-change (infinitive learning) ---
  ["acordarse","sich erinnern",false,"ar"],["agradecer","danken",false,"er"],["alcanzar","erreichen",false,"ar"],
  ["alegrarse","sich freuen",false,"ar"],["andar","gehen/laufen",false,"ar"],["apagar","ausschalten",false,"ar"],
  ["avanzar","vorankommen",false,"ar"],["abrazar","umarmen",false,"ar"],["calentar","erhitzen",false,"ar"],
  ["cargar","laden",false,"ar"],["colgar","aufhängen",false,"ar"],["comunicar","mitteilen",false,"ar"],
  ["confesar","gestehen",false,"ar"],["confiar","vertrauen",false,"ar"],["criticar","kritisieren",false,"ar"],
  ["dedicar","widmen",false,"ar"],["demostrar","beweisen",false,"ar"],["descargar","herunterladen",false,"ar"],
  ["distinguir","unterscheiden",false,"ir"],["educar","erziehen",false,"ar"],["enviar","senden",false,"ar"],
  ["entregar","übergeben",false,"ar"],["equivocarse","sich irren",false,"ar"],["exigir","fordern",false,"ir"],
  ["guiar","führen",false,"ar"],["huir","fliehen",false,"ir"],["impedir","verhindern",false,"ir"],
  ["incluir","einschließen",false,"ir"],["indicar","hinweisen",false,"ar"],["introducir","einführen",false,"ir"],
  ["juzgar","urteilen",false,"ar"],["lanzar","werfen",false,"ar"],["lograr","erreichen/schaffen",false,"ar"],
  ["marcar","markieren/wählen",false,"ar"],["medir","messen",false,"ir"],["merecer","verdienen",false,"er"],
  ["negar","verneinen",false,"ar"],["obedecer","gehorchen",false,"er"],["oponerse","sich widersetzen",false,"er"],
  ["pertenecer","gehören",false,"er"],["permanecer","bleiben",false,"er"],["perseguir","verfolgen",false,"ir"],
  ["pescar","angeln",false,"ar"],["poseer","besitzen",false,"er"],["predecir","vorhersagen",false,"ir"],
  ["prohibir","verbieten",false,"ir"],["proteger","schützen",false,"er"],["provocar","provozieren",false,"ar"],
  ["publicar","veröffentlichen",false,"ar"],["rechazar","ablehnen",false,"ar"],["recoger","aufsammeln/abholen",false,"er"],
  ["recomendar","empfehlen",false,"ar"],["reducir","reduzieren",false,"ir"],["resolver","lösen",false,"er"],
  ["rogar","bitten/flehen",false,"ar"],["sentar","setzen",false,"ar"],["soltar","loslassen",false,"ar"],
  ["sonar","klingen/läuten",false,"ar"],["sonreír","lächeln",false,"ir"],["soñar","träumen",false,"ar"],
  ["sostener","stützen/halten",false,"er"],["sugerir","vorschlagen",false,"ir"],["tropezar","stolpern",false,"ar"],
  ["vaciar","leeren",false,"ar"],["valer","wert sein",false,"er"],["vencer","besiegen",false,"er"],
  ["verificar","überprüfen",false,"ar"],["volar","fliegen",false,"ar"],["colocar","platzieren",false,"ar"],
  ["variar","variieren",false,"ar"],["dedicarse","sich widmen",false,"ar"]
];
