/* Frecuencia — deck expansion band E (fills to 2000+). Rows [es, de, pos]. Deduped at runtime. */
window.WORDS = (window.WORDS||[]).concat([
  // ---- society, state, politics ----
  ["sociedad","Gesellschaft","S(f)"],["comunidad","Gemeinschaft","S(f)"],["población","Bevölkerung","S(f)"],
  ["nación","Nation","S(f)"],["estado","Staat","S(m)"],["patria","Vaterland / Heimat","S(f)"],
  ["ciudadano","Bürger","S(m)"],["política","Politik","S(f)"],["político","Politiker","S(m)"],
  ["partido","Partei","S(m)"],["gobierno","Regierung","S(m)"],["ministro","Minister","S(m)"],
  ["alcalde","Bürgermeister","S(m)"],["elección","Wahl","S(f)"],["voto","Stimme (Wahl)","S(m)"],
  ["derecho","Recht","S(m)"],["deber","Pflicht","S(m)"],["libertad","Freiheit","S(f)"],
  ["revolución","Revolution","S(f)"],["manifestación","Demonstration","S(f)"],["huelga","Streik","S(f)"],
  ["bandera","Flagge","S(f)"],["himno","Hymne","S(m)"],["frontera","Grenze","S(f)"],
  ["ejército","Heer / Armee","S(m)"],["guerra","Krieg","S(f)"],["paz","Frieden","S(f)"],
  ["arma","Waffe","S(f)"],["batalla","Schlacht","S(f)"],["enemigo","Feind","S(m)"],
  ["aliado","Verbündeter","S(m)"],["víctima","Opfer","S(f)"],["héroe","Held","S(m)"],
  // ---- law & crime ----
  ["ley","Gesetz","S(f)"],["norma","Regel / Norm","S(f)"],["justicia","Justiz","S(f)"],
  ["tribunal","Gericht","S(m)"],["juicio","Prozess / Urteil","S(m)"],["delito","Straftat","S(m)"],
  ["crimen","Verbrechen","S(m)"],["ladrón","Dieb","S(m)"],["robo","Raub / Diebstahl","S(m)"],
  ["asesino","Mörder","S(m)"],["cárcel","Gefängnis","S(f)"],["prisión","Haft / Gefängnis","S(f)"],
  ["castigo","Strafe","S(m)"],["multa","Geldstrafe / Bußgeld","S(f)"],["culpa","Schuld","S(f)"],
  ["inocente","unschuldig","Adj"],["culpable","schuldig","Adj"],["testigo","Zeuge","S(m)"],
  ["prueba","Beweis","S(f)"],["denuncia","Anzeige","S(f)"],["peligro","Gefahr","S(m)"],
  // ---- more verbs ----
  ["nacer","geboren werden","V"],["morir","sterben","V"],["matar","töten","V"],
  ["herir","verletzen","V"],["curar","heilen","V"],["salvar","retten","V"],
  ["cuidar","pflegen / betreuen","V"],["criar","aufziehen / großziehen","V"],["educar","erziehen","V"],
  ["castigar","bestrafen","V"],["premiar","belohnen","V"],["perdonar","verzeihen","V"],
  ["culpar","beschuldigen","V"],["acusar","anklagen","V"],["juzgar","urteilen / beurteilen","V"],
  ["robar","stehlen","V"],["esconder","verstecken","V"],["descubrir","entdecken","V"],
  ["encontrar","finden","V"],["buscar","suchen","V"],["perder","verlieren","V"],
  ["recuperar","zurückgewinnen / sich erholen","V"],["reparar","reparieren","V"],["mejorar","verbessern","V"],
  ["empeorar","verschlechtern","V"],["crecer","wachsen","V"],["reducir","verringern","V"],
  ["aumentar","erhöhen","V"],["dividir","teilen","V"],["multiplicar","multiplizieren","V"],
  ["sumar","addieren","V"],["restar","subtrahieren","V"],["repartir","verteilen","V"],
  ["compartir","teilen (miteinander)","V"],["prestar","leihen","V"],["devolver","zurückgeben","V"],
  ["regalar","schenken","V"],["heredar","erben","V"],["poseer","besitzen","V"],
  ["adquirir","erwerben","V"],["alquilar","mieten / vermieten","V"],["gastar","ausgeben","V"],
  ["invertir","investieren","V"],["cobrar","kassieren / berechnen","V"],["deber","schulden","V"],
  ["firmar","unterschreiben","V"],["rellenar","ausfüllen","V"],["apuntar","notieren / zielen","V"],
  ["anotar","aufschreiben","V"],["señalar","hinweisen","V"],["subrayar","unterstreichen","V"],
  ["traducir","übersetzen","V"],["corregir","korrigieren","V"],["mejorar","verbessern","V"],
  ["elegir","wählen","V"],["escoger","auswählen","V"],["votar","wählen / abstimmen","V"],
  ["proponer","vorschlagen","V"],["sugerir","vorschlagen / andeuten","V"],["recomendar","empfehlen","V"],
  ["aconsejar","raten","V"],["ordenar","befehlen / ordnen","V"],["mandar","befehlen / schicken","V"],
  ["obedecer","gehorchen","V"],["cumplir","erfüllen / einhalten","V"],["fallar","versagen","V"],
  ["intentar","versuchen","V"],["conseguir","schaffen","V"],["renunciar","verzichten / kündigen","V"],
  ["rendirse","aufgeben","V"],["insistir","beharren","V"],["continuar","fortfahren","V"],
  // ---- more adjectives ----
  ["sano","gesund","Adj"],["enfermo","krank","Adj"],["fuerte","stark","Adj"],
  ["débil","schwach","Adj"],["vivo","lebendig / wach","Adj"],["muerto","tot","Adj"],
  ["despierto","wach","Adj"],["dormido","schlafend","Adj"],["hambriento","hungrig","Adj"],
  ["borracho","betrunken","Adj"],["ciego","blind","Adj"],["sordo","taub","Adj"],
  ["rubio","blond","Adj"],["moreno","dunkelhaarig / braun","Adj"],["calvo","kahl / glatzköpfig","Adj"],
  ["guapo","gutaussehend","Adj"],["hermoso","wunderschön","Adj"],["elegante","elegant","Adj"],
  ["sucio","schmutzig","Adj"],["limpio","sauber","Adj"],["nuevo","neu","Adj"],
  ["usado","gebraucht","Adj"],["roto","kaputt","Adj"],["entero","ganz / heil","Adj"],
  ["maduro","reif","Adj"],["verde","unreif / grün","Adj"],["podrido","verfault","Adj"],
  ["salado","salzig","Adj"],["dulce","süß","Adj"],["amargo","bitter","Adj"],
  ["ácido","sauer","Adj"],["picante","scharf","Adj"],["rico","lecker / reich","Adj"],
  ["asqueroso","ekelhaft","Adj"],["delicioso","köstlich","Adj"],["ruidoso","laut / lärmend","Adj"],
  ["silencioso","leise / still","Adj"],["oscuro","dunkel","Adj"],["brillante","glänzend / brillant","Adj"],
  ["colorido","bunt","Adj"],["pálido","blass","Adj"],["gris","grau","Adj"],
  ["marrón","braun","Adj"],["rosa","rosa","Adj"],["morado","lila","Adj"],
  ["naranja","orange","Adj"],["dorado","golden","Adj"],["plateado","silbern","Adj"],
  ["profundo","tief","Adj"],["superficial","oberflächlich","Adj"],["denso","dicht","Adj"],
  ["vacío","leer","Adj"],["lleno","voll","Adj"],["abierto","offen","Adj"],
  ["cerrado","geschlossen","Adj"],["libre","frei","Adj"],["ocupado","besetzt / beschäftigt","Adj"],
  ["disponible","verfügbar","Adj"],["listo","bereit","Adj"],["preparado","vorbereitet","Adj"],
  // ---- more nouns: everyday ----
  ["cosa","Sache","S(f)"],["asunto","Angelegenheit","S(m)"],["problema","Problem","S(m)"],
  ["solución","Lösung","S(f)"],["error","Fehler","S(m)"],["fallo","Fehler / Panne","S(m)"],
  ["éxito","Erfolg","S(m)"],["fracaso","Misserfolg","S(m)"],["intento","Versuch","S(m)"],
  ["esfuerzo","Anstrengung","S(m)"],["ayuda","Hilfe","S(f)"],["apoyo","Unterstützung","S(m)"],
  ["consejo","Rat","S(m)"],["aviso","Hinweis / Warnung","S(m)"],["mensaje","Nachricht","S(m)"],
  ["noticia","Nachricht (Neuigkeit)","S(f)"],["información","Information","S(f)"],["pregunta","Frage","S(f)"],
  ["respuesta","Antwort","S(f)"],["duda","Zweifel","S(f)"],["broma","Scherz","S(f)"],
  ["chiste","Witz","S(m)"],["risa","Lachen","S(f)"],["llanto","Weinen","S(m)"],
  ["grito","Schrei","S(m)"],["silencio","Stille","S(m)"],["ruido","Lärm / Geräusch","S(m)"],
  ["sonido","Klang / Geräusch","S(m)"],["olor","Geruch","S(m)"],["sabor","Geschmack","S(m)"],
  ["tacto","Tastsinn","S(m)"],["vista","Sicht / Sehen","S(f)"],["mirada","Blick","S(f)"],
  ["sonrisa","Lächeln","S(f)"],["beso","Kuss","S(m)"],["abrazo","Umarmung","S(m)"],
  ["saludo","Gruß","S(m)"],["despedida","Abschied","S(f)"],["encuentro","Treffen / Begegnung","S(m)"],
  ["visita","Besuch","S(f)"],["invitación","Einladung","S(f)"],["regalo","Geschenk","S(m)"],
  ["sorpresa","Überraschung","S(f)"],["celebración","Feier","S(f)"],["boda","Hochzeit","S(f)"],
  ["funeral","Beerdigung","S(m)"],["nacimiento","Geburt","S(m)"],["muerte","Tod","S(f)"],
  ["vida","Leben","S(f)"],["juventud","Jugend","S(f)"],["vejez","Alter (hohes)","S(f)"],
  ["infancia","Kindheit","S(f)"],["edad","Alter","S(f)"],["generación","Generation","S(f)"],
  // ---- directions & positions ----
  ["dirección","Richtung / Adresse","S(f)"],["derecha","rechte Seite","S(f)"],["izquierda","linke Seite","S(f)"],
  ["frente","Vorderseite / gegenüber","S(m)"],["fondo","Hintergrund / Boden","S(m)"],["borde","Rand","S(m)"],
  ["límite","Grenze / Limit","S(m)"],["extremo","Ende / Extrem","S(m)"],["medio","Mitte","S(m)"],
  ["interior","Innere","S(m)"],["exterior","Äußere","S(m)"],["superficie","Oberfläche","S(f)"],
  ["altura","Höhe","S(f)"],["cima","Gipfel","S(f)"],["base","Basis / Grundlage","S(f)"],
  ["rincón","Ecke (innen)","S(m)"],["hueco","Lücke / Hohlraum","S(m)"],["agujero","Loch","S(m)"],
  // ---- more prepositions / connectors / adverbs ----
  ["encima de","auf / über","Präp"],["debajo de","unter","Präp"],["delante de","vor","Präp"],
  ["detrás de","hinter","Präp"],["al lado de","neben","Präp"],["cerca de","in der Nähe von","Präp"],
  ["lejos de","weit von","Präp"],["dentro de","innerhalb von","Präp"],["fuera de","außerhalb von","Präp"],
  ["en medio de","mitten in","Präp"],["frente a","gegenüber","Präp"],["en contra de","gegen","Präp"],
  ["a favor de","für / zugunsten","Präp"],["respecto a","bezüglich","Präp"],["en cuanto a","was … betrifft","Präp"],
  ["a partir de","ab / von … an","Präp"],["a lo largo de","entlang / im Laufe von","Präp"],["por medio de","mittels","Präp"],
  ["asimismo","ebenso","Adv"],["igualmente","ebenfalls","Adv"],["por otro lado","andererseits","Adv"],
  ["por un lado","einerseits","Adv"],["en primer lugar","erstens","Adv"],["en resumen","zusammenfassend","Adv"],
  ["por ejemplo","zum Beispiel","Adv"],["es decir","das heißt","Adv"],["en efecto","in der Tat","Adv"],
  ["por desgracia","leider","Adv"],["por suerte","zum Glück","Adv"],["a propósito","übrigens / absichtlich","Adv"],
  ["de repente","plötzlich","Adv"],["poco después","kurz danach","Adv"],["hace poco","vor kurzem","Adv"],
  ["dentro de poco","in Kürze","Adv"],["a tiempo","rechtzeitig","Adv"],["de golpe","auf einen Schlag","Adv"],
  ["a menudo","oft","Adv"],["rara vez","selten","Adv"],["casi nunca","fast nie","Adv"],
  ["casi siempre","fast immer","Adv"],["por completo","vollständig","Adv"],["en absoluto","überhaupt nicht","Adv"]
]);
