/* Spanish frequency deck — top ~500 words ordered by usage frequency.
   Row format: [es, de, pos, exampleES, exampleDE]
   pos codes: Art=Artikel, Pron=Pronomen, Präp=Präposition, Konj=Konjunktion,
   V=Verb, S=Substantiv, Adj=Adjektiv, Adv=Adverb, Num=Zahlwort, Interj=Ausruf */
window.WORDS = [
  ["que","dass / der, die, das","Konj/Pron","Dijo que vendría.","Er sagte, dass er kommen würde."],
  ["de","von / aus","Präp","La casa de mi madre.","Das Haus meiner Mutter."],
  ["no","nein / nicht","Adv","No tengo tiempo.","Ich habe keine Zeit."],
  ["a","zu / nach / an","Präp","Voy a casa.","Ich gehe nach Hause."],
  ["la","die (fem.)","Art","La mesa es grande.","Der Tisch ist groß."],
  ["el","der (mask.)","Art","El perro duerme.","Der Hund schläft."],
  ["es","ist","V","Ella es médica.","Sie ist Ärztin."],
  ["y","und","Konj","Pan y agua.","Brot und Wasser."],
  ["en","in / auf","Präp","Estoy en casa.","Ich bin zu Hause."],
  ["lo","es / das (Pron.)","Pron","No lo sé.","Ich weiß es nicht."],
  ["un","ein (mask.)","Art","Un libro nuevo.","Ein neues Buch."],
  ["por","für / durch / wegen","Präp","Gracias por todo.","Danke für alles."],
  ["qué","was / welche(r)","Pron","¿Qué quieres?","Was willst du?"],
  ["me","mich / mir","Pron","Me llamo Ana.","Ich heiße Ana."],
  ["una","eine (fem.)","Art","Una idea buena.","Eine gute Idee."],
  ["te","dich / dir","Pron","Te quiero.","Ich liebe dich."],
  ["los","die (Plural mask.)","Art","Los niños juegan.","Die Kinder spielen."],
  ["se","sich","Pron","Se lava las manos.","Er wäscht sich die Hände."],
  ["con","mit","Präp","Café con leche.","Kaffee mit Milch."],
  ["para","für / um zu","Präp","Es para ti.","Es ist für dich."],
  ["mi","mein","Pron","Mi hermano vive aquí.","Mein Bruder wohnt hier."],
  ["está","ist (Zustand/Ort)","V","¿Dónde está el baño?","Wo ist die Toilette?"],
  ["si","wenn / falls","Konj","Si llueve, no salgo.","Wenn es regnet, gehe ich nicht raus."],
  ["bien","gut","Adv","Todo está bien.","Alles ist gut."],
  ["pero","aber","Konj","Quiero, pero no puedo.","Ich will, aber ich kann nicht."],
  ["yo","ich","Pron","Yo trabajo aquí.","Ich arbeite hier."],
  ["eso","das (dort)","Pron","Eso no es verdad.","Das ist nicht wahr."],
  ["las","die (Plural fem.)","Art","Las flores son rojas.","Die Blumen sind rot."],
  ["sí","ja","Adv","Sí, claro.","Ja, klar."],
  ["su","sein / ihr","Pron","Su coche es azul.","Sein Auto ist blau."],
  ["tu","dein","Pron","Tu casa es bonita.","Dein Haus ist schön."],
  ["aquí","hier","Adv","Ven aquí.","Komm her."],
  ["del","von dem (de+el)","Präp","La puerta del coche.","Die Tür des Autos."],
  ["al","zu dem (a+el)","Präp","Voy al mercado.","Ich gehe zum Markt."],
  ["como","wie","Adv/Konj","Es alto como tú.","Er ist groß wie du."],
  ["le","ihm / ihr","Pron","Le doy el libro.","Ich gebe ihm das Buch."],
  ["más","mehr","Adv","Quiero más agua.","Ich will mehr Wasser."],
  ["esto","dies","Pron","Esto es importante.","Dies ist wichtig."],
  ["ya","schon / bereits","Adv","Ya terminé.","Ich bin schon fertig."],
  ["todo","alles / ganz","Pron/Adj","Todo el día.","Den ganzen Tag."],
  ["esta","diese","Pron/Adj","Esta noche salimos.","Heute Abend gehen wir aus."],
  ["vamos","wir gehen / los","V","¡Vamos ya!","Los jetzt!"],
  ["muy","sehr","Adv","Es muy fácil.","Es ist sehr leicht."],
  ["hay","es gibt","V","Hay mucha gente.","Es gibt viele Leute."],
  ["ahora","jetzt","Adv","Ahora no puedo.","Jetzt kann ich nicht."],
  ["algo","etwas","Pron","¿Quieres algo?","Willst du etwas?"],
  ["estoy","ich bin","V","Estoy cansado.","Ich bin müde."],
  ["tengo","ich habe","V","Tengo hambre.","Ich habe Hunger."],
  ["nos","uns","Pron","Nos vemos mañana.","Wir sehen uns morgen."],
  ["tú","du","Pron","¿Tú qué opinas?","Was meinst du?"],
  ["nada","nichts","Pron","No hay nada.","Es gibt nichts."],
  ["cuando","wenn / als","Konj","Cuando llegué, dormías.","Als ich ankam, hast du geschlafen."],
  ["ha","hat (Hilfsverb)","V","Ella ha comido.","Sie hat gegessen."],
  ["este","dieser","Pron/Adj","Este libro es mío.","Dieses Buch ist meins."],
  ["sé","ich weiß","V","No sé nada.","Ich weiß nichts."],
  ["estás","du bist","V","¿Cómo estás?","Wie geht es dir?"],
  ["así","so","Adv","No se hace así.","So macht man das nicht."],
  ["puedo","ich kann","V","No puedo ir.","Ich kann nicht gehen."],
  ["cómo","wie","Adv","¿Cómo te llamas?","Wie heißt du?"],
  ["quiero","ich will / möchte","V","Quiero café.","Ich möchte Kaffee."],
  ["solo","nur / allein","Adv/Adj","Estoy solo.","Ich bin allein."],
  ["soy","ich bin","V","Soy de Alemania.","Ich bin aus Deutschland."],
  ["tiene","er/sie hat","V","Tiene dos hijos.","Sie hat zwei Kinder."],
  ["gracias","danke","Interj","Muchas gracias.","Vielen Dank."],
  ["o","oder","Konj","¿Té o café?","Tee oder Kaffee?"],
  ["él","er","Pron","Él es mi amigo.","Er ist mein Freund."],
  ["hacer","machen / tun","V","¿Qué vas a hacer?","Was wirst du machen?"],
  ["mucho","viel","Adv/Adj","Te quiero mucho.","Ich liebe dich sehr."],
  ["quién","wer","Pron","¿Quién es?","Wer ist das?"],
  ["porque","weil","Konj","No voy porque llueve.","Ich gehe nicht, weil es regnet."],
  ["por qué","warum","Adv","¿Por qué lloras?","Warum weinst du?"],
  ["cosa","Sache / Ding","S(f)","Es otra cosa.","Das ist etwas anderes."],
  ["puede","er/sie kann","V","Puede esperar.","Es kann warten."],
  ["tan","so (+ Adj.)","Adv","Es tan bonito.","Es ist so schön."],
  ["dos","zwei","Num","Tengo dos gatos.","Ich habe zwei Katzen."],
  ["ser","sein","V","Quiero ser feliz.","Ich will glücklich sein."],
  ["tener","haben","V","Hay que tener paciencia.","Man muss Geduld haben."],
  ["hombre","Mann","S(m)","Ese hombre es alto.","Dieser Mann ist groß."],
  ["ver","sehen","V","Quiero ver la película.","Ich will den Film sehen."],
  ["ir","gehen","V","Tengo que ir.","Ich muss gehen."],
  ["dónde","wo","Adv","¿Dónde vives?","Wo wohnst du?"],
  ["vez","Mal","S(f)","Otra vez, por favor.","Noch einmal, bitte."],
  ["nadie","niemand","Pron","No vino nadie.","Es kam niemand."],
  ["mucha","viel (fem.)","Adj","Hay mucha nieve.","Es gibt viel Schnee."],
  ["mismo","selbe(r) / selbst","Adj","Es lo mismo.","Es ist dasselbe."],
  ["decir","sagen","V","¿Qué quieres decir?","Was willst du sagen?"],
  ["dios","Gott","S(m)","Dios mío.","Mein Gott."],
  ["entonces","dann / also","Adv","Entonces, ¿qué hacemos?","Also, was machen wir?"],
  ["hasta","bis","Präp","Hasta mañana.","Bis morgen."],
  ["poco","wenig","Adv/Adj","Un poco de sal.","Ein bisschen Salz."],
  ["señor","Herr","S(m)","Buenos días, señor.","Guten Tag, mein Herr."],
  ["ellos","sie (Plural)","Pron","Ellos viven aquí.","Sie wohnen hier."],
  ["esa","jene (fem.)","Pron/Adj","Esa mujer canta.","Jene Frau singt."],
  ["cada","jede(r)","Adj","Cada día es distinto.","Jeder Tag ist anders."],
  ["vida","Leben","S(f)","Así es la vida.","So ist das Leben."],
  ["nunca","nie","Adv","Nunca es tarde.","Es ist nie zu spät."],
  ["también","auch","Adv","Yo también voy.","Ich gehe auch."],
  ["cuál","welche(r)","Pron","¿Cuál prefieres?","Welchen bevorzugst du?"],
  ["favor","Gefallen","S(m)","Por favor, ayúdame.","Bitte hilf mir."],
  ["poder","können / Macht","V/S(m)","Vas a poder hacerlo.","Du wirst es schaffen können."],
  ["días","Tage","S(m)","Buenos días.","Guten Morgen."],
  ["querer","wollen / lieben","V","Querer es poder.","Wollen ist können."],
  ["parte","Teil","S(f)","¿De parte de quién?","Von wem (aus)?"],
  ["esos","jene (Pl.)","Pron/Adj","Esos zapatos son míos.","Jene Schuhe sind meine."],
  ["momento","Moment","S(m)","Un momento, por favor.","Einen Moment, bitte."],
  ["antes","vorher / früher","Adv","Antes vivía en Madrid.","Früher wohnte ich in Madrid."],
  ["gente","Leute","S(f)","Hay mucha gente.","Es sind viele Leute."],
  ["mujer","Frau","S(f)","La mujer sonríe.","Die Frau lächelt."],
  ["casa","Haus","S(f)","Voy a casa.","Ich gehe nach Hause."],
  ["igual","gleich / egal","Adj/Adv","Me da igual.","Es ist mir egal."],
  ["saber","wissen / können","V","Quiero saber la verdad.","Ich will die Wahrheit wissen."],
  ["cielo","Himmel","S(m)","El cielo está azul.","Der Himmel ist blau."],
  ["ni","weder / nicht einmal","Konj","Ni tú ni yo.","Weder du noch ich."],
  ["haber","haben (Hilfsverb)","V","Debe haber un error.","Es muss einen Fehler geben."],
  ["dijo","sagte","V","Ella dijo que sí.","Sie sagte ja."],
  ["hola","hallo","Interj","¡Hola! ¿Qué tal?","Hallo! Wie geht's?"],
  ["fue","war / ging","V","Fue un buen día.","Es war ein guter Tag."],
  ["ellas","sie (fem. Pl.)","Pron","Ellas cantan bien.","Sie singen gut."],
  ["tiempo","Zeit / Wetter","S(m)","No tengo tiempo.","Ich habe keine Zeit."],
  ["desde","seit / von … an","Präp","Desde ayer.","Seit gestern."],
  ["grande","groß","Adj","Una casa grande.","Ein großes Haus."],
  ["siempre","immer","Adv","Siempre llegas tarde.","Du kommst immer zu spät."],
  ["sobre","über / auf","Präp","El libro sobre la mesa.","Das Buch auf dem Tisch."],
  ["mañana","morgen / Morgen","Adv/S(f)","Hasta mañana.","Bis morgen."],
  ["creo","ich glaube","V","Creo que sí.","Ich glaube ja."],
  ["padre","Vater","S(m)","Mi padre trabaja.","Mein Vater arbeitet."],
  ["mundo","Welt","S(m)","Todo el mundo lo sabe.","Alle Welt weiß es."],
  ["amor","Liebe","S(m)","El amor es ciego.","Liebe macht blind."],
  ["mejor","besser / beste(r)","Adj/Adv","Es mejor así.","So ist es besser."],
  ["debe","muss / soll","V","Debe estudiar más.","Er muss mehr lernen."],
  ["allí","dort","Adv","Está allí.","Er ist dort."],
  ["hecho","gemacht / Tatsache","V/S(m)","Está hecho.","Es ist erledigt."],
  ["cual","welche(r) (rel.)","Pron","La razón por la cual vine.","Der Grund, aus dem ich kam."],
  ["madre","Mutter","S(f)","Quiero a mi madre.","Ich liebe meine Mutter."],
  ["voy","ich gehe","V","Voy al trabajo.","Ich gehe zur Arbeit."],
  ["forma","Form / Weise","S(f)","De alguna forma.","Auf irgendeine Weise."],
  ["parece","scheint","V","Parece fácil.","Es scheint leicht."],
  ["verdad","Wahrheit","S(f)","Di la verdad.","Sag die Wahrheit."],
  ["mí","mich / mir (betont)","Pron","Es para mí.","Es ist für mich."],
  ["luego","später / dann","Adv","Hasta luego.","Bis später."],
  ["cualquier","irgendein","Adj","En cualquier momento.","In jedem Moment."],
  ["ese","jener","Pron/Adj","Ese es mi coche.","Das ist mein Auto."],
  ["dar","geben","V","Voy a dar un paseo.","Ich mache einen Spaziergang."],
  ["problema","Problem","S(m)","No hay problema.","Kein Problem."],
  ["tanto","so viel","Adv","No comas tanto.","Iss nicht so viel."],
  ["trabajo","Arbeit","S(m)","Me gusta mi trabajo.","Ich mag meine Arbeit."],
  ["quería","wollte","V","Quería verte.","Ich wollte dich sehen."],
  ["hace","macht / vor (Zeit)","V","Hace frío.","Es ist kalt."],
  ["primera","erste (fem.)","Num","La primera vez.","Das erste Mal."],
  ["señora","Dame / Frau","S(f)","Buenas tardes, señora.","Guten Tag, gnädige Frau."],
  ["tres","drei","Num","Tengo tres perros.","Ich habe drei Hunde."],
  ["realmente","wirklich","Adv","Realmente no lo sé.","Ich weiß es wirklich nicht."],
  ["noche","Nacht","S(f)","Buenas noches.","Gute Nacht."],
  ["tal","solch / so","Adj","¿Qué tal?","Wie geht's?"],
  ["cuenta","Rechnung / Konto","S(f)","La cuenta, por favor.","Die Rechnung, bitte."],
  ["hago","ich mache","V","No sé qué hago.","Ich weiß nicht, was ich tue."],
  ["primero","zuerst / erste(r)","Adv/Num","Primero come.","Iss zuerst."],
  ["mundo","Welt","S(m)","Un mundo mejor.","Eine bessere Welt."],
  ["mano","Hand","S(f)","Dame la mano.","Gib mir die Hand."],
  ["donde","wo (rel.)","Adv","La ciudad donde nací.","Die Stadt, wo ich geboren wurde."],
  ["puedes","du kannst","V","¿Puedes ayudarme?","Kannst du mir helfen?"],
  ["nosotros","wir","Pron","Nosotros llegamos hoy.","Wir kommen heute an."],
  ["hoy","heute","Adv","Hoy es lunes.","Heute ist Montag."],
  ["cierto","sicher / gewiss","Adj","Es cierto.","Es ist wahr."],
  ["encontrar","finden","V","No puedo encontrar las llaves.","Ich kann die Schlüssel nicht finden."],
  ["ojos","Augen","S(m)","Tiene ojos verdes.","Sie hat grüne Augen."],
  ["cabeza","Kopf","S(f)","Me duele la cabeza.","Mein Kopf tut weh."],
  ["esperar","warten / hoffen","V","Voy a esperar aquí.","Ich warte hier."],
  ["hombres","Männer","S(m)","Los hombres trabajan.","Die Männer arbeiten."],
  ["mejor","besser","Adv","Canta mejor que yo.","Sie singt besser als ich."],
  ["cuánto","wie viel","Adv","¿Cuánto cuesta?","Wie viel kostet das?"],
  ["hablar","sprechen / reden","V","Quiero hablar contigo.","Ich will mit dir reden."],
  ["nuevo","neu","Adj","Un coche nuevo.","Ein neues Auto."],
  ["escuchar","zuhören / hören","V","Me gusta escuchar música.","Ich höre gern Musik."],
  ["seguro","sicher","Adj","¿Estás seguro?","Bist du sicher?"],
  ["deja","lass / lässt","V","Déjame en paz.","Lass mich in Ruhe."],
  ["manera","Art / Weise","S(f)","De ninguna manera.","Auf keinen Fall."],
  ["contra","gegen","Präp","Estoy en contra.","Ich bin dagegen."],
  ["tarde","spät / Nachmittag","Adv/S(f)","Es tarde.","Es ist spät."],
  ["fin","Ende","S(m)","Al fin y al cabo.","Letztendlich."],
  ["lugar","Ort / Platz","S(m)","En primer lugar.","An erster Stelle."],
  ["semana","Woche","S(f)","La semana pasada.","Letzte Woche."],
  ["dinero","Geld","S(m)","No tengo dinero.","Ich habe kein Geld."],
  ["preguntar","fragen","V","Voy a preguntar.","Ich werde fragen."],
  ["cara","Gesicht","S(f)","Tiene buena cara.","Sie sieht gut aus."],
  ["chico","Junge","S(m)","Ese chico es simpático.","Dieser Junge ist nett."],
  ["chica","Mädchen","S(f)","La chica lee un libro.","Das Mädchen liest ein Buch."],
  ["conmigo","mit mir","Pron","Ven conmigo.","Komm mit mir."],
  ["ayuda","Hilfe","S(f)","Necesito ayuda.","Ich brauche Hilfe."],
  ["mientras","während","Konj","Canta mientras cocina.","Sie singt, während sie kocht."],
  ["dejar","lassen / verlassen","V","No quiero dejar esto.","Ich will das nicht aufgeben."],
  ["pensar","denken","V","Debo pensar en ello.","Ich muss darüber nachdenken."],
  ["agua","Wasser","S(f)","Un vaso de agua.","Ein Glas Wasser."],
  ["llegar","ankommen","V","Voy a llegar tarde.","Ich komme zu spät."],
  ["padres","Eltern","S(m)","Mis padres viajan.","Meine Eltern reisen."],
  ["pueblo","Dorf / Volk","S(m)","Vivo en un pueblo.","Ich wohne in einem Dorf."],
  ["encima","oben / darüber","Adv","Está encima de la mesa.","Es liegt auf dem Tisch."],
  ["tipo","Typ / Art","S(m)","¿Qué tipo de música?","Welche Art von Musik?"],
  ["comer","essen","V","Vamos a comer.","Lass uns essen."],
  ["horas","Stunden","S(f)","Faltan dos horas.","Es fehlen zwei Stunden."],
  ["gustar","gefallen / mögen","V","Me gusta el mar.","Ich mag das Meer."],
  ["hija","Tochter","S(f)","Tengo una hija.","Ich habe eine Tochter."],
  ["hijo","Sohn","S(m)","Su hijo estudia.","Ihr Sohn studiert."],
  ["mira","schau / sieh","V","Mira esto.","Schau dir das an."],
  ["dice","sagt","V","Ella dice la verdad.","Sie sagt die Wahrheit."],
  ["salir","hinausgehen / ausgehen","V","Quiero salir esta noche.","Ich will heute Abend ausgehen."],
  ["mal","schlecht / schlimm","Adv/Adj","Me siento mal.","Ich fühle mich schlecht."],
  ["clase","Klasse / Unterricht","S(f)","Voy a clase.","Ich gehe zum Unterricht."],
  ["cinco","fünf","Num","Son las cinco.","Es ist fünf Uhr."],
  ["número","Nummer / Zahl","S(m)","¿Cuál es tu número?","Wie ist deine Nummer?"],
  ["punto","Punkt","S(m)","Hasta cierto punto.","Bis zu einem gewissen Punkt."],
  ["fuerte","stark","Adj","Es muy fuerte.","Er ist sehr stark."],
  ["encontró","fand","V","Encontró la solución.","Er fand die Lösung."],
  ["vino","kam / Wein","V/S(m)","Vino a verme.","Er kam, um mich zu sehen."],
  ["general","allgemein","Adj","Por lo general.","Im Allgemeinen."],
  ["pasar","passieren / vorbeigehen","V","¿Qué va a pasar?","Was wird passieren?"],
  ["mayor","größer / älter","Adj","Mi hermano mayor.","Mein älterer Bruder."],
  ["poner","stellen / legen / setzen","V","Voy a poner la mesa.","Ich decke den Tisch."],
  ["libro","Buch","S(m)","Leo un libro.","Ich lese ein Buch."],
  ["cerca","nah / in der Nähe","Adv","Vivo cerca.","Ich wohne in der Nähe."],
  ["puerta","Tür","S(f)","Cierra la puerta.","Mach die Tür zu."],
  ["fácil","einfach / leicht","Adj","Es muy fácil.","Es ist sehr leicht."],
  ["llevar","tragen / bringen","V","Voy a llevar el coche.","Ich nehme das Auto."],
  ["quizás","vielleicht","Adv","Quizás mañana.","Vielleicht morgen."],
  ["deben","müssen / sollen","V","Deben esperar.","Sie müssen warten."],
  ["amigo","Freund","S(m)","Es mi mejor amigo.","Er ist mein bester Freund."],
  ["ah","ah / ach","Interj","¡Ah, ya entiendo!","Ach, jetzt verstehe ich!"],
  ["última","letzte (fem.)","Adj","La última vez.","Das letzte Mal."],
  ["semana","Woche","S(f)","Esta semana trabajo mucho.","Diese Woche arbeite ich viel."],
  ["frente","Stirn / Front","S(f)","Frente a la casa.","Gegenüber dem Haus."],
  ["escuela","Schule","S(f)","Los niños van a la escuela.","Die Kinder gehen zur Schule."],
  ["real","echt / königlich","Adj","Una historia real.","Eine wahre Geschichte."],
  ["cuatro","vier","Num","Son las cuatro.","Es ist vier Uhr."],
  ["campo","Feld / Land","S(m)","Vivimos en el campo.","Wir leben auf dem Land."],
  ["comida","Essen / Mahlzeit","S(f)","La comida está lista.","Das Essen ist fertig."],
  ["historia","Geschichte","S(f)","Cuéntame una historia.","Erzähl mir eine Geschichte."],
  ["conocer","kennen / kennenlernen","V","Quiero conocer España.","Ich will Spanien kennenlernen."],
  ["seguir","folgen / weitermachen","V","Voy a seguir aquí.","Ich bleibe weiter hier."],
  ["existir","existieren","V","Debe existir una razón.","Es muss einen Grund geben."],
  ["hora","Stunde / Uhrzeit","S(f)","¿Qué hora es?","Wie spät ist es?"],
  ["ciudad","Stadt","S(f)","Vivo en la ciudad.","Ich wohne in der Stadt."],
  ["importante","wichtig","Adj","Es muy importante.","Es ist sehr wichtig."],
  ["empezar","anfangen / beginnen","V","Vamos a empezar.","Wir fangen an."],
  ["bueno","gut","Adj","Es un buen día.","Es ist ein guter Tag."],
  ["poder","Macht / können","S(m)/V","Está en el poder.","Er ist an der Macht."],
  ["entender","verstehen","V","No te entiendo.","Ich verstehe dich nicht."],
  ["viejo","alt","Adj","Un coche viejo.","Ein altes Auto."],
  ["mientras","während","Konj","Espera mientras llamo.","Warte, während ich anrufe."],
  ["ganar","gewinnen / verdienen","V","Quiero ganar el partido.","Ich will das Spiel gewinnen."],
  ["perder","verlieren","V","No quiero perder.","Ich will nicht verlieren."],
  ["semejante","ähnlich / derartig","Adj","Nunca vi algo semejante.","So etwas sah ich nie."],
  ["morir","sterben","V","Todos vamos a morir.","Wir alle werden sterben."],
  ["blanco","weiß","Adj","Un vestido blanco.","Ein weißes Kleid."],
  ["negro","schwarz","Adj","Un gato negro.","Eine schwarze Katze."],
  ["rojo","rot","Adj","Un coche rojo.","Ein rotes Auto."],
  ["libre","frei","Adj","¿Estás libre hoy?","Bist du heute frei?"],
  ["pequeño","klein","Adj","Un perro pequeño.","Ein kleiner Hund."],
  ["joven","jung","Adj","Es muy joven.","Er ist sehr jung."],
  ["difícil","schwierig","Adj","El examen fue difícil.","Die Prüfung war schwierig."],
  ["escribir","schreiben","V","Voy a escribir una carta.","Ich schreibe einen Brief."],
  ["leer","lesen","V","Me gusta leer.","Ich lese gern."],
  ["abrir","öffnen","V","¿Puedes abrir la ventana?","Kannst du das Fenster öffnen?"],
  ["cerrar","schließen","V","Voy a cerrar la puerta.","Ich schließe die Tür."],
  ["andar","gehen / laufen","V","Vamos a andar un poco.","Lass uns ein bisschen gehen."],
  ["correr","rennen / laufen","V","Me gusta correr.","Ich laufe gern."],
  ["jugar","spielen","V","Los niños quieren jugar.","Die Kinder wollen spielen."],
  ["cantar","singen","V","Ella sabe cantar.","Sie kann singen."],
  ["bailar","tanzen","V","Vamos a bailar.","Lass uns tanzen."],
  ["comprar","kaufen","V","Quiero comprar pan.","Ich möchte Brot kaufen."],
  ["vender","verkaufen","V","Van a vender la casa.","Sie verkaufen das Haus."],
  ["pagar","bezahlen","V","Yo voy a pagar.","Ich bezahle."],
  ["trabajar","arbeiten","V","Trabajo de lunes a viernes.","Ich arbeite von Montag bis Freitag."],
  ["estudiar","lernen / studieren","V","Tengo que estudiar.","Ich muss lernen."],
  ["viajar","reisen","V","Me encanta viajar.","Ich reise sehr gern."],
  ["dormir","schlafen","V","Necesito dormir.","Ich muss schlafen."],
  ["despertar","aufwecken / aufwachen","V","Me despierto temprano.","Ich wache früh auf."],
  ["sentir","fühlen","V","Lo siento mucho.","Es tut mir sehr leid."],
  ["recordar","sich erinnern","V","No lo recuerdo.","Ich erinnere mich nicht daran."],
  ["olvidar","vergessen","V","No lo olvides.","Vergiss es nicht."],
  ["cambiar","ändern / wechseln","V","Quiero cambiar de trabajo.","Ich will den Job wechseln."],
  ["ayudar","helfen","V","¿Me puedes ayudar?","Kannst du mir helfen?"],
  ["necesitar","brauchen","V","Necesito tu ayuda.","Ich brauche deine Hilfe."],
  ["usar","benutzen","V","¿Puedo usar tu teléfono?","Darf ich dein Telefon benutzen?"],
  ["buscar","suchen","V","Estoy buscando trabajo.","Ich suche Arbeit."],
  ["mostrar","zeigen","V","Te voy a mostrar algo.","Ich zeige dir etwas."],
  ["llamar","rufen / anrufen","V","Voy a llamar a mi madre.","Ich rufe meine Mutter an."],
  ["preguntar","fragen","V","Déjame preguntar.","Lass mich fragen."],
  ["responder","antworten","V","No sé qué responder.","Ich weiß nicht, was ich antworten soll."],
  ["contar","zählen / erzählen","V","Te voy a contar algo.","Ich erzähle dir etwas."],
  ["mirar","schauen / ansehen","V","Mira el cielo.","Schau in den Himmel."],
  ["oír","hören","V","No te puedo oír.","Ich kann dich nicht hören."],
  ["sentarse","sich setzen","V","Siéntate, por favor.","Setz dich, bitte."],
  ["levantarse","aufstehen","V","Me levanto a las siete.","Ich stehe um sieben auf."],
  ["caer","fallen","V","Ten cuidado, no te caigas.","Pass auf, fall nicht."],
  ["subir","hochgehen / steigen","V","Vamos a subir la escalera.","Wir gehen die Treppe hoch."],
  ["bajar","runtergehen / senken","V","Voy a bajar ahora.","Ich komme jetzt runter."],
  ["entrar","hineingehen / eintreten","V","¿Puedo entrar?","Darf ich hereinkommen?"],
  ["volver","zurückkehren","V","Voy a volver pronto.","Ich komme bald zurück."],
  ["traer","bringen","V","¿Puedes traer agua?","Kannst du Wasser bringen?"],
  ["sacar","herausnehmen / herausholen","V","Voy a sacar la basura.","Ich bringe den Müll raus."],
  ["meter","hineinstecken / hineintun","V","Mete la ropa en la maleta.","Steck die Kleidung in den Koffer."],
  ["conseguir","erreichen / bekommen","V","Voy a conseguir el trabajo.","Ich werde den Job bekommen."],
  ["intentar","versuchen","V","Voy a intentarlo.","Ich werde es versuchen."],
  ["lograr","schaffen / erreichen","V","Logré terminar.","Ich habe es geschafft, fertig zu werden."],
  ["deber","müssen / schulden","V","Debes descansar.","Du musst dich ausruhen."],
  ["parecer","scheinen / erscheinen","V","Parece cansado.","Er wirkt müde."],
  ["quedar","bleiben / übrig bleiben","V","Quedan dos días.","Es bleiben zwei Tage."],
  ["gustar","gefallen","V","¿Te gusta?","Gefällt es dir?"],
  ["importar","wichtig sein / stören","V","No me importa.","Es ist mir egal."],
  ["cuerpo","Körper","S(m)","Cuida tu cuerpo.","Pass auf deinen Körper auf."],
  ["corazón","Herz","S(m)","Me duele el corazón.","Mein Herz tut weh."],
  ["pie","Fuß","S(m)","Me duele el pie.","Mein Fuß tut weh."],
  ["brazo","Arm","S(m)","Me rompí el brazo.","Ich habe mir den Arm gebrochen."],
  ["pelo","Haar","S(m)","Tiene el pelo largo.","Sie hat lange Haare."],
  ["boca","Mund","S(f)","Cierra la boca.","Mach den Mund zu."],
  ["diente","Zahn","S(m)","Me duele un diente.","Mir tut ein Zahn weh."],
  ["sangre","Blut","S(f)","Donó sangre.","Er spendete Blut."],
  ["comida","Essen","S(f)","La comida está rica.","Das Essen ist lecker."],
  ["pan","Brot","S(m)","Compro pan fresco.","Ich kaufe frisches Brot."],
  ["leche","Milch","S(f)","Un vaso de leche.","Ein Glas Milch."],
  ["café","Kaffee","S(m)","Un café, por favor.","Einen Kaffee, bitte."],
  ["vino","Wein","S(m)","Una copa de vino.","Ein Glas Wein."],
  ["carne","Fleisch","S(f)","No como carne.","Ich esse kein Fleisch."],
  ["fruta","Obst / Frucht","S(f)","Como mucha fruta.","Ich esse viel Obst."],
  ["huevo","Ei","S(m)","Quiero un huevo frito.","Ich möchte ein Spiegelei."],
  ["sal","Salz","S(f)","Falta sal.","Es fehlt Salz."],
  ["azúcar","Zucker","S(m/f)","¿Con azúcar?","Mit Zucker?"],
  ["mesa","Tisch","S(f)","Pon la mesa.","Deck den Tisch."],
  ["silla","Stuhl","S(f)","Siéntate en la silla.","Setz dich auf den Stuhl."],
  ["cama","Bett","S(f)","Voy a la cama.","Ich gehe ins Bett."],
  ["ventana","Fenster","S(f)","Abre la ventana.","Mach das Fenster auf."],
  ["coche","Auto","S(m)","Mi coche es viejo.","Mein Auto ist alt."],
  ["calle","Straße","S(f)","Vivo en esta calle.","Ich wohne in dieser Straße."],
  ["camino","Weg","S(m)","Es un largo camino.","Es ist ein langer Weg."],
  ["tren","Zug","S(m)","El tren llega tarde.","Der Zug kommt zu spät."],
  ["avión","Flugzeug","S(m)","El avión despega.","Das Flugzeug hebt ab."],
  ["playa","Strand","S(f)","Vamos a la playa.","Wir gehen an den Strand."],
  ["mar","Meer","S(m)","El mar está tranquilo.","Das Meer ist ruhig."],
  ["montaña","Berg","S(f)","Subimos la montaña.","Wir bestiegen den Berg."],
  ["árbol","Baum","S(m)","El árbol es alto.","Der Baum ist hoch."],
  ["flor","Blume","S(f)","Una flor roja.","Eine rote Blume."],
  ["sol","Sonne","S(m)","Hace sol.","Die Sonne scheint."],
  ["luna","Mond","S(f)","La luna es blanca.","Der Mond ist weiß."],
  ["luz","Licht","S(f)","Enciende la luz.","Mach das Licht an."],
  ["fuego","Feuer","S(m)","El fuego es peligroso.","Feuer ist gefährlich."],
  ["aire","Luft","S(m)","Necesito aire fresco.","Ich brauche frische Luft."],
  ["lluvia","Regen","S(f)","La lluvia no para.","Der Regen hört nicht auf."],
  ["nieve","Schnee","S(f)","Me gusta la nieve.","Ich mag Schnee."],
  ["viento","Wind","S(m)","Hace mucho viento.","Es ist sehr windig."],
  ["frío","kalt / Kälte","Adj/S(m)","Tengo frío.","Mir ist kalt."],
  ["calor","Wärme / Hitze","S(m)","Hace calor.","Es ist heiß."],
  ["color","Farbe","S(m)","¿Qué color prefieres?","Welche Farbe magst du lieber?"],
  ["verde","grün","Adj","Un campo verde.","Ein grünes Feld."],
  ["azul","blau","Adj","El mar es azul.","Das Meer ist blau."],
  ["amarillo","gelb","Adj","El sol es amarillo.","Die Sonne ist gelb."],
  ["dinero","Geld","S(m)","El dinero no es todo.","Geld ist nicht alles."],
  ["precio","Preis","S(m)","¿Cuál es el precio?","Wie hoch ist der Preis?"],
  ["tienda","Geschäft / Laden","S(f)","Voy a la tienda.","Ich gehe zum Laden."],
  ["mercado","Markt","S(m)","Compro fruta en el mercado.","Ich kaufe Obst auf dem Markt."],
  ["trabajo","Arbeit / Job","S(m)","Busco trabajo.","Ich suche Arbeit."],
  ["oficina","Büro","S(f)","Trabajo en una oficina.","Ich arbeite in einem Büro."],
  ["empresa","Unternehmen / Firma","S(f)","Trabaja en una empresa grande.","Er arbeitet in einer großen Firma."],
  ["dinero","Geld","S(m)","Necesito más dinero.","Ich brauche mehr Geld."],
  ["teléfono","Telefon","S(m)","¿Cuál es tu teléfono?","Wie ist deine Telefonnummer?"],
  ["ordenador","Computer","S(m)","Uso el ordenador para trabajar.","Ich benutze den Computer zum Arbeiten."],
  ["música","Musik","S(f)","Me encanta la música.","Ich liebe Musik."],
  ["película","Film","S(f)","Vamos a ver una película.","Lass uns einen Film ansehen."],
  ["juego","Spiel","S(m)","Es solo un juego.","Es ist nur ein Spiel."],
  ["idioma","Sprache","S(m)","El español es un idioma bonito.","Spanisch ist eine schöne Sprache."],
  ["palabra","Wort","S(f)","No entiendo esta palabra.","Ich verstehe dieses Wort nicht."],
  ["nombre","Name","S(m)","¿Cuál es tu nombre?","Wie ist dein Name?"],
  ["pregunta","Frage","S(f)","Tengo una pregunta.","Ich habe eine Frage."],
  ["respuesta","Antwort","S(f)","No hay respuesta.","Es gibt keine Antwort."],
  ["ejemplo","Beispiel","S(m)","Por ejemplo, el pan.","Zum Beispiel Brot."],
  ["razón","Grund / Recht","S(f)","Tienes razón.","Du hast recht."],
  ["idea","Idee","S(f)","Buena idea.","Gute Idee."],
  ["verdad","Wahrheit","S(f)","¿Es verdad?","Ist das wahr?"],
  ["error","Fehler","S(m)","Fue un error.","Es war ein Fehler."],
  ["suerte","Glück","S(f)","¡Buena suerte!","Viel Glück!"],
  ["miedo","Angst","S(m)","Tengo miedo.","Ich habe Angst."],
  ["alegría","Freude","S(f)","¡Qué alegría!","Was für eine Freude!"],
  ["dolor","Schmerz","S(m)","Siento mucho dolor.","Ich habe große Schmerzen."],
  ["salud","Gesundheit","S(f)","¡Salud!","Prost! / Gesundheit!"],
  ["enfermo","krank","Adj","Estoy enfermo.","Ich bin krank."],
  ["médico","Arzt","S(m)","Voy al médico.","Ich gehe zum Arzt."],
  ["hospital","Krankenhaus","S(m)","Está en el hospital.","Er ist im Krankenhaus."],
  ["familia","Familie","S(f)","Amo a mi familia.","Ich liebe meine Familie."],
  ["hermano","Bruder","S(m)","Mi hermano es alto.","Mein Bruder ist groß."],
  ["hermana","Schwester","S(f)","Mi hermana canta.","Meine Schwester singt."],
  ["abuelo","Großvater","S(m)","Mi abuelo tiene 80 años.","Mein Großvater ist 80 Jahre alt."],
  ["abuela","Großmutter","S(f)","Mi abuela cocina bien.","Meine Großmutter kocht gut."],
  ["niño","Kind / Junge","S(m)","El niño juega.","Das Kind spielt."],
  ["niña","Mädchen","S(f)","La niña ríe.","Das Mädchen lacht."],
  ["esposo","Ehemann","S(m)","Mi esposo trabaja fuera.","Mein Mann arbeitet auswärts."],
  ["esposa","Ehefrau","S(f)","Su esposa es profesora.","Seine Frau ist Lehrerin."],
  ["amigo","Freund","S(m)","Somos buenos amigos.","Wir sind gute Freunde."],
  ["gato","Katze","S(m)","El gato duerme.","Die Katze schläft."],
  ["perro","Hund","S(m)","El perro ladra.","Der Hund bellt."],
  ["pájaro","Vogel","S(m)","El pájaro canta.","Der Vogel singt."],
  ["pez","Fisch","S(m)","El pez nada.","Der Fisch schwimmt."],
  ["caballo","Pferd","S(m)","El caballo corre.","Das Pferd rennt."],
  ["año","Jahr","S(m)","Feliz año nuevo.","Frohes neues Jahr."],
  ["mes","Monat","S(m)","El mes que viene.","Nächsten Monat."],
  ["día","Tag","S(m)","Buen día.","Guten Tag."],
  ["hoy","heute","Adv","Hoy hace sol.","Heute scheint die Sonne."],
  ["ayer","gestern","Adv","Ayer llovió.","Gestern hat es geregnet."],
  ["temprano","früh","Adv","Me levanto temprano.","Ich stehe früh auf."],
  ["pronto","bald","Adv","Hasta pronto.","Bis bald."],
  ["lunes","Montag","S(m)","El lunes trabajo.","Am Montag arbeite ich."],
  ["viernes","Freitag","S(m)","El viernes salgo.","Am Freitag gehe ich aus."],
  ["hora","Uhrzeit","S(f)","Es hora de ir.","Es ist Zeit zu gehen."],
  ["minuto","Minute","S(m)","Espera un minuto.","Warte eine Minute."],
  ["mundo","Welt","S(m)","Quiero ver el mundo.","Ich will die Welt sehen."],
  ["país","Land / Staat","S(m)","España es un país bonito.","Spanien ist ein schönes Land."],
  ["gobierno","Regierung","S(m)","El gobierno decide.","Die Regierung entscheidet."],
  ["guerra","Krieg","S(f)","La guerra es terrible.","Krieg ist schrecklich."],
  ["paz","Frieden","S(f)","Queremos la paz.","Wir wollen Frieden."],
  ["ley","Gesetz","S(f)","Es la ley.","Es ist das Gesetz."],
  ["derecho","Recht / gerade","S(m)/Adj","Tienes derecho a hablar.","Du hast das Recht zu sprechen."],
  ["fuerza","Kraft / Stärke","S(f)","No tengo fuerza.","Ich habe keine Kraft."],
  ["poder","Macht","S(m)","El poder corrompe.","Macht korrumpiert."],
  ["grupo","Gruppe","S(m)","Somos un grupo grande.","Wir sind eine große Gruppe."],
  ["parte","Teil","S(f)","Una parte del pastel.","Ein Teil des Kuchens."],
  ["final","Ende / letzte(r)","S(m)/Adj","Al final todo salió bien.","Am Ende ging alles gut."],
  ["principio","Anfang / Prinzip","S(m)","Al principio fue difícil.","Am Anfang war es schwer."],
  ["centro","Zentrum / Mitte","S(m)","Vivo en el centro.","Ich wohne im Zentrum."],
  ["norte","Norden","S(m)","Viven en el norte.","Sie leben im Norden."],
  ["sur","Süden","S(m)","Vamos al sur.","Wir fahren in den Süden."],
  ["lado","Seite","S(m)","Al lado de la iglesia.","Neben der Kirche."],
  ["derecha","rechts / Rechte","S(f)","Gira a la derecha.","Bieg nach rechts ab."],
  ["izquierda","links / Linke","S(f)","La puerta de la izquierda.","Die linke Tür."],
  ["arriba","oben","Adv","Sube arriba.","Geh nach oben."],
  ["abajo","unten","Adv","Te espero abajo.","Ich warte unten auf dich."],
  ["dentro","drinnen / innerhalb","Adv","Está dentro de la caja.","Es ist in der Schachtel."],
  ["fuera","draußen","Adv","Los niños juegan fuera.","Die Kinder spielen draußen."],
  ["lejos","weit","Adv","Está muy lejos.","Es ist sehr weit weg."],
  ["alto","hoch / groß","Adj","Un edificio alto.","Ein hohes Gebäude."],
  ["bajo","niedrig / klein / unter","Adj/Präp","Un techo bajo.","Eine niedrige Decke."],
  ["largo","lang","Adj","Un camino largo.","Ein langer Weg."],
  ["corto","kurz","Adj","Un pelo corto.","Kurze Haare."],
  ["ancho","breit","Adj","Un río ancho.","Ein breiter Fluss."],
  ["lento","langsam","Adj","Es muy lento.","Es ist sehr langsam."],
  ["rápido","schnell","Adj","Un coche rápido.","Ein schnelles Auto."],
  ["caliente","heiß","Adj","El café está caliente.","Der Kaffee ist heiß."],
  ["limpio","sauber","Adj","La casa está limpia.","Das Haus ist sauber."],
  ["sucio","schmutzig","Adj","Tus manos están sucias.","Deine Hände sind schmutzig."],
  ["lleno","voll","Adj","El vaso está lleno.","Das Glas ist voll."],
  ["vacío","leer","Adj","La botella está vacía.","Die Flasche ist leer."],
  ["bonito","schön / hübsch","Adj","¡Qué bonito!","Wie schön!"],
  ["feo","hässlich","Adj","Es un poco feo.","Es ist etwas hässlich."],
  ["rico","reich / lecker","Adj","La comida está rica.","Das Essen ist lecker."],
  ["pobre","arm","Adj","Es una familia pobre.","Es ist eine arme Familie."],
  ["caro","teuer","Adj","Es demasiado caro.","Es ist zu teuer."],
  ["barato","billig / günstig","Adj","Es muy barato.","Es ist sehr günstig."],
  ["feliz","glücklich","Adj","Soy muy feliz.","Ich bin sehr glücklich."],
  ["triste","traurig","Adj","Estoy triste hoy.","Ich bin heute traurig."],
  ["contento","zufrieden / froh","Adj","Estoy contento.","Ich bin zufrieden."],
  ["cansado","müde","Adj","Estoy muy cansado.","Ich bin sehr müde."],
  ["ocupado","beschäftigt","Adj","Estoy ocupado ahora.","Ich bin gerade beschäftigt."],
  ["listo","fertig / clever","Adj","¿Estás listo?","Bist du fertig?"],
  ["posible","möglich","Adj","Es posible.","Es ist möglich."],
  ["necesario","notwendig / nötig","Adj","No es necesario.","Es ist nicht nötig."],
  ["cierto","sicher / wahr","Adj","Es cierto.","Es ist wahr."],
  ["falso","falsch","Adj","Es falso.","Es ist falsch."],
  ["claro","klar","Adj/Adv","¡Claro que sí!","Aber klar!"],
  ["oscuro","dunkel","Adj","Está muy oscuro.","Es ist sehr dunkel."],
  ["nuevo","neu","Adj","Un teléfono nuevo.","Ein neues Telefon."],
  ["último","letzte(r)","Adj","El último día.","Der letzte Tag."],
  ["próximo","nächste(r)","Adj","La próxima semana.","Nächste Woche."],
  ["mucho","viel","Adj/Adv","Hay mucho que hacer.","Es gibt viel zu tun."],
  ["poco","wenig","Adj/Adv","Tengo poco tiempo.","Ich habe wenig Zeit."],
  ["todo","alles","Pron/Adj","Todo va bien.","Alles läuft gut."],
  ["mucha","viel (fem.)","Adj","Hay mucha luz.","Es ist viel Licht."],
  ["algunos","einige","Adj/Pron","Algunos días llueve.","An manchen Tagen regnet es."],
  ["otro","andere(r)","Adj/Pron","Quiero otro.","Ich will einen anderen."],
  ["cada","jede(r)","Adj","Cada persona es única.","Jeder Mensch ist einzigartig."],
  ["ambos","beide","Adj/Pron","Ambos tienen razón.","Beide haben recht."],
  ["ninguno","kein(er)","Adj/Pron","No quiero ninguno.","Ich will keinen."],
  ["bastante","ziemlich / genug","Adv/Adj","Es bastante caro.","Es ist ziemlich teuer."],
  ["demasiado","zu (viel)","Adv","Es demasiado tarde.","Es ist zu spät."],
  ["casi","fast","Adv","Casi termino.","Ich bin fast fertig."],
  ["quizá","vielleicht","Adv","Quizá venga.","Vielleicht kommt er."],
  ["tal vez","vielleicht","Adv","Tal vez mañana.","Vielleicht morgen."],
  ["seguramente","sicherlich","Adv","Seguramente llega tarde.","Sicherlich kommt er zu spät."],
  ["realmente","wirklich","Adv","Realmente me gusta.","Es gefällt mir wirklich."],
  ["solamente","nur","Adv","Solamente quiero agua.","Ich will nur Wasser."],
  ["además","außerdem","Adv","Además, hace frío.","Außerdem ist es kalt."],
  ["tampoco","auch nicht","Adv","Yo tampoco lo sé.","Ich weiß es auch nicht."],
  ["todavía","noch","Adv","Todavía no llega.","Er kommt noch nicht."],
  ["aún","noch / sogar","Adv","Aún es temprano.","Es ist noch früh."],
  ["pronto","bald","Adv","Vuelvo pronto.","Ich komme bald zurück."],
  ["despacio","langsam","Adv","Habla despacio, por favor.","Sprich bitte langsam."],
  ["juntos","zusammen","Adv","Estamos juntos.","Wir sind zusammen."],
  ["quizás","vielleicht","Adv","Quizás sí.","Vielleicht ja."],
  ["afuera","draußen","Adv","Vamos afuera.","Lass uns nach draußen gehen."],
  ["adentro","hinein / drinnen","Adv","Entra adentro.","Geh hinein."],
  ["cerca","nah","Adv","La tienda está cerca.","Der Laden ist nah."],
  ["primero","zuerst","Adv","Primero lávate las manos.","Wasch dir zuerst die Hände."],
  ["después","danach / später","Adv","Después hablamos.","Wir reden später."],
  ["luego","dann / später","Adv","Nos vemos luego.","Wir sehen uns später."],
  ["entonces","dann / also","Adv","¿Entonces vienes?","Kommst du also?"],
  ["mientras","währenddessen","Adv","Mientras, descansa.","Ruh dich inzwischen aus."],
  ["durante","während (Präp.)","Präp","Durante la noche.","Während der Nacht."],
  ["antes","vorher","Adv","Llámame antes.","Ruf mich vorher an."],
  ["según","laut / gemäß","Präp","Según el mapa, es aquí.","Laut Karte ist es hier."],
  ["entre","zwischen","Präp","Entre tú y yo.","Zwischen dir und mir."],
  ["hacia","in Richtung / gegen","Präp","Vamos hacia el norte.","Wir fahren Richtung Norden."],
  ["sin","ohne","Präp","Café sin azúcar.","Kaffee ohne Zucker."],
  ["bajo","unter","Präp","Bajo la mesa.","Unter dem Tisch."],
  ["tras","nach / hinter","Präp","Día tras día.","Tag für Tag."],
  ["mediante","mittels / durch","Präp","Lo resolvió mediante el diálogo.","Er löste es durch Dialog."],
  ["excepto","außer","Präp","Todos vinieron excepto Ana.","Alle kamen außer Ana."],
  ["aunque","obwohl","Konj","Salgo aunque llueva.","Ich gehe raus, obwohl es regnet."],
  ["sino","sondern","Konj","No es rojo, sino azul.","Es ist nicht rot, sondern blau."],
  ["pues","denn / also","Konj","Pues no lo sé.","Also, ich weiß es nicht."],
  ["mientras que","während (Gegensatz)","Konj","Yo leo, mientras que él duerme.","Ich lese, während er schläft."],
  ["por eso","deshalb","Adv","Por eso llegué tarde.","Deshalb kam ich zu spät."],
  ["sin embargo","dennoch / jedoch","Adv","Es caro; sin embargo, lo compro.","Es ist teuer; dennoch kaufe ich es."],
  ["es decir","das heißt","Adv","Mañana, es decir el lunes.","Morgen, das heißt am Montag."],
  ["por supuesto","natürlich","Adv","Por supuesto que sí.","Aber natürlich."],
  ["de repente","plötzlich","Adv","De repente empezó a llover.","Plötzlich fing es an zu regnen."],
  ["a veces","manchmal","Adv","A veces cocino.","Manchmal koche ich."],
  ["a menudo","oft","Adv","Voy al gimnasio a menudo.","Ich gehe oft ins Fitnessstudio."],
  ["en seguida","sofort","Adv","Vuelvo en seguida.","Ich bin sofort zurück."],
  ["por fin","endlich","Adv","¡Por fin llegaste!","Endlich bist du da!"],
  ["sobre todo","vor allem","Adv","Me gusta la fruta, sobre todo la manzana.","Ich mag Obst, vor allem Äpfel."],
  ["por lo menos","wenigstens","Adv","Por lo menos lo intentaste.","Wenigstens hast du es versucht."],
  ["seis","sechs","Num","Son las seis.","Es ist sechs Uhr."],
  ["siete","sieben","Num","Tengo siete libros.","Ich habe sieben Bücher."],
  ["ocho","acht","Num","A las ocho de la mañana.","Um acht Uhr morgens."],
  ["nueve","neun","Num","Faltan nueve días.","Es fehlen neun Tage."],
  ["diez","zehn","Num","Diez euros, por favor.","Zehn Euro, bitte."],
  ["cien","hundert","Num","Cien personas vinieron.","Hundert Leute kamen."],
  ["mil","tausend","Num","Mil gracias.","Tausend Dank."],
  ["primero","erste(r)","Num","El primero de mayo.","Der erste Mai."],
  ["segundo","zweite(r) / Sekunde","Num/S(m)","El segundo piso.","Der zweite Stock."],
  ["medio","halb / Mitte","Adj/S(m)","Media hora.","Eine halbe Stunde."],
  ["doble","doppelt","Adj","El doble de dinero.","Das doppelte Geld."],
  ["gracias","danke","Interj","Gracias por venir.","Danke fürs Kommen."],
  ["adiós","tschüss / auf Wiedersehen","Interj","Adiós, hasta mañana.","Tschüss, bis morgen."],
  ["perdón","Entschuldigung","Interj","Perdón por llegar tarde.","Entschuldigung, dass ich zu spät bin."],
  ["disculpe","Entschuldigung (höflich)","Interj","Disculpe, ¿dónde está la estación?","Entschuldigung, wo ist der Bahnhof?"],
  ["claro","klar / natürlich","Interj","—¿Vienes? —¡Claro!","—Kommst du? —Klar!"],
  ["vale","okay / einverstanden","Interj","Vale, nos vemos.","Okay, wir sehen uns."],
  ["oye","hör mal","Interj","Oye, ¿tienes un momento?","Hör mal, hast du kurz Zeit?"],
  ["bueno","na gut / also","Interj","Bueno, empecemos.","Also gut, fangen wir an."],
  ["ojalá","hoffentlich","Interj","Ojalá haga sol.","Hoffentlich scheint die Sonne."],
  ["enhorabuena","Glückwunsch","Interj","¡Enhorabuena por tu trabajo!","Glückwunsch zu deinem Job!"],
  ["preciso","genau / präzise","Adj","En el momento preciso.","Im genauen Moment."],
  ["cuánto","wie viel","Adv","¿Cuánto tiempo tienes?","Wie viel Zeit hast du?"],
  ["cuántos","wie viele","Adv","¿Cuántos años tienes?","Wie alt bist du?"],
  ["cuándo","wann","Adv","¿Cuándo llegas?","Wann kommst du an?"],
  ["adónde","wohin","Adv","¿Adónde vas?","Wohin gehst du?"],
  ["cerdo","Schwein","S(m)","Comemos carne de cerdo.","Wir essen Schweinefleisch."],
  ["pollo","Huhn / Hähnchen","S(m)","Quiero pollo con arroz.","Ich möchte Hähnchen mit Reis."],
  ["arroz","Reis","S(m)","El arroz está listo.","Der Reis ist fertig."],
  ["queso","Käse","S(m)","Un bocadillo de queso.","Ein Käsebrötchen."],
  ["sopa","Suppe","S(f)","La sopa está caliente.","Die Suppe ist heiß."],
  ["verdura","Gemüse","S(f)","Como mucha verdura.","Ich esse viel Gemüse."],
  ["manzana","Apfel","S(f)","Una manzana al día.","Ein Apfel am Tag."],
  ["naranja","Orange","S(f)","Un zumo de naranja.","Ein Orangensaft."],
  ["cerveza","Bier","S(f)","Una cerveza fría.","Ein kaltes Bier."],
  ["ropa","Kleidung","S(f)","Necesito ropa nueva.","Ich brauche neue Kleidung."],
  ["zapato","Schuh","S(m)","Estos zapatos son cómodos.","Diese Schuhe sind bequem."],
  ["camisa","Hemd","S(f)","Lleva una camisa blanca.","Er trägt ein weißes Hemd."],
  ["pantalón","Hose","S(m)","Compré un pantalón negro.","Ich kaufte eine schwarze Hose."],
  ["sombrero","Hut","S(m)","Lleva un sombrero grande.","Er trägt einen großen Hut."],
  ["reloj","Uhr","S(m)","Mi reloj está roto.","Meine Uhr ist kaputt."],
  ["llave","Schlüssel","S(f)","No encuentro las llaves.","Ich finde die Schlüssel nicht."],
  ["papel","Papier","S(m)","Necesito una hoja de papel.","Ich brauche ein Blatt Papier."],
  ["carta","Brief / Karte","S(f)","Escribí una carta.","Ich schrieb einen Brief."],
  ["periódico","Zeitung","S(m)","Leo el periódico.","Ich lese die Zeitung."],
  ["noticia","Nachricht","S(f)","Buenas noticias.","Gute Nachrichten."],
  ["foto","Foto","S(f)","Saca una foto.","Mach ein Foto."],
  ["regalo","Geschenk","S(m)","Un regalo para ti.","Ein Geschenk für dich."],
  ["fiesta","Fest / Party","S(f)","Vamos a la fiesta.","Wir gehen zur Party."],
  ["viaje","Reise","S(m)","¡Buen viaje!","Gute Reise!"],
  ["habitación","Zimmer","S(f)","Mi habitación es pequeña.","Mein Zimmer ist klein."],
  ["baño","Bad / Toilette","S(m)","¿Dónde está el baño?","Wo ist die Toilette?"],
  ["cocina","Küche","S(f)","Cocino en la cocina.","Ich koche in der Küche."],
  ["jardín","Garten","S(m)","Tenemos un jardín grande.","Wir haben einen großen Garten."],
  ["edificio","Gebäude","S(m)","Un edificio muy antiguo.","Ein sehr altes Gebäude."],
  ["iglesia","Kirche","S(f)","La iglesia es del siglo XV.","Die Kirche ist aus dem 15. Jahrhundert."],
  ["puente","Brücke","S(m)","Cruzamos el puente.","Wir überquerten die Brücke."],
  ["río","Fluss","S(m)","El río es muy largo.","Der Fluss ist sehr lang."],
  ["bosque","Wald","S(m)","Caminamos por el bosque.","Wir gingen durch den Wald."],
  ["isla","Insel","S(f)","Vivimos en una isla.","Wir leben auf einer Insel."],
  ["mundo","Welt","S(m)","El mundo es grande.","Die Welt ist groß."],
  ["gente","Leute","S(f)","La gente es amable.","Die Leute sind freundlich."],
  ["persona","Person","S(f)","Es una buena persona.","Er ist ein guter Mensch."],
  ["cuerpo","Körper","S(m)","El cuerpo humano.","Der menschliche Körper."],
  ["mente","Verstand / Geist","S(f)","Una mente abierta.","Ein offener Geist."],
  ["alma","Seele","S(f)","Con toda mi alma.","Von ganzem Herzen."],
  ["nivel","Niveau / Ebene","S(m)","Un nivel alto.","Ein hohes Niveau."],
  ["estado","Zustand / Staat","S(m)","Está en buen estado.","Es ist in gutem Zustand."],
  ["caso","Fall","S(m)","En ese caso, sí.","In dem Fall, ja."],
  ["orden","Ordnung / Befehl","S(m/f)","Todo está en orden.","Alles ist in Ordnung."],
  ["clase","Art / Klasse","S(f)","Todo tipo de clase.","Jede Art von Klasse."],
  ["modo","Art / Weise","S(m)","De todos modos.","Auf jeden Fall."],
  ["cambio","Wechsel / Wechselgeld","S(m)","Un cambio de planes.","Eine Planänderung."],
  ["ayuda","Hilfe","S(f)","Pide ayuda.","Bitte um Hilfe."],
  ["cuidado","Vorsicht / Pflege","S(m)","¡Ten cuidado!","Sei vorsichtig!"],
  ["intento","Versuch","S(m)","En el primer intento.","Beim ersten Versuch."],
  ["deseo","Wunsch","S(m)","Un deseo de cumpleaños.","Ein Geburtstagswunsch."],
  ["sueño","Traum / Schlaf","S(m)","Tengo sueño.","Ich bin müde (habe Schlaf)."],
  ["gana","Lust","S(f)","Tengo ganas de bailar.","Ich habe Lust zu tanzen."],
  ["esfuerzo","Anstrengung / Mühe","S(m)","Vale la pena el esfuerzo.","Die Mühe lohnt sich."],
  ["cuidar","pflegen / aufpassen","V","Voy a cuidar al niño.","Ich passe auf das Kind auf."],
  ["crear","schaffen / erstellen","V","Quiero crear algo nuevo.","Ich will etwas Neues schaffen."],
  ["construir","bauen","V","Van a construir una casa.","Sie bauen ein Haus."],
  ["romper","brechen / kaputtmachen","V","No rompas el vaso.","Mach das Glas nicht kaputt."],
  ["nacer","geboren werden","V","Nací en 1990.","Ich wurde 1990 geboren."],
  ["crecer","wachsen","V","Los niños crecen rápido.","Kinder wachsen schnell."],
  ["vivir","leben / wohnen","V","Vivo en Madrid.","Ich wohne in Madrid."],
  ["beber","trinken","V","Voy a beber agua.","Ich trinke Wasser."],
  ["cocinar","kochen","V","Sé cocinar paella.","Ich kann Paella kochen."],
  ["lavar","waschen","V","Tengo que lavar la ropa.","Ich muss die Wäsche waschen."],
  ["limpiar","putzen / reinigen","V","Voy a limpiar la casa.","Ich putze das Haus."],
  ["romper","zerbrechen","V","Se rompió el plato.","Der Teller ist zerbrochen."],
  ["ganar","gewinnen","V","Nuestro equipo va a ganar.","Unser Team wird gewinnen."],
  ["viajar","reisen","V","Vamos a viajar a España.","Wir reisen nach Spanien."],
  ["descansar","sich ausruhen","V","Necesito descansar.","Ich muss mich ausruhen."],
  ["esperar","warten / hoffen","V","Espero que sí.","Ich hoffe ja."],
  ["desear","wünschen","V","Te deseo lo mejor.","Ich wünsche dir alles Gute."],
  ["preferir","bevorzugen","V","Prefiero el té.","Ich bevorzuge Tee."],
  ["decidir","entscheiden","V","Tienes que decidir.","Du musst dich entscheiden."],
  ["elegir","wählen / auswählen","V","Es difícil elegir.","Es ist schwer zu wählen."],
  ["permitir","erlauben","V","¿Me permites pasar?","Erlaubst du mir durchzugehen?"],
  ["prohibir","verbieten","V","Está prohibido fumar.","Rauchen ist verboten."],
  ["deber","sollen / müssen","V","Deberías dormir más.","Du solltest mehr schlafen."],
  ["ocurrir","geschehen / passieren","V","¿Qué ocurrió?","Was ist passiert?"],
  ["suceder","geschehen","V","Nada sucede sin razón.","Nichts geschieht ohne Grund."],
  ["resultar","sich ergeben / ausfallen","V","Resultó ser verdad.","Es stellte sich als wahr heraus."],
  ["significar","bedeuten","V","¿Qué significa esto?","Was bedeutet das?"],
  ["explicar","erklären","V","¿Me lo puedes explicar?","Kannst du es mir erklären?"],
  ["describir","beschreiben","V","Describe la escena.","Beschreib die Szene."],
  ["recibir","empfangen / erhalten","V","Recibí tu carta.","Ich habe deinen Brief erhalten."],
  ["enviar","senden / schicken","V","Voy a enviar un mensaje.","Ich schicke eine Nachricht."],
  ["mandar","schicken / befehlen","V","Me mandó un regalo.","Er schickte mir ein Geschenk."],
  ["ofrecer","anbieten","V","Me ofreció ayuda.","Er bot mir Hilfe an."],
  ["aceptar","akzeptieren / annehmen","V","Acepto tu oferta.","Ich nehme dein Angebot an."],
  ["rechazar","ablehnen","V","Rechazó la propuesta.","Er lehnte den Vorschlag ab."],
  ["prometer","versprechen","V","Te lo prometo.","Ich verspreche es dir."],
  ["repetir","wiederholen","V","¿Puedes repetir, por favor?","Kannst du das bitte wiederholen?"],
  ["continuar","fortsetzen / weitermachen","V","Vamos a continuar mañana.","Wir machen morgen weiter."],
  ["terminar","beenden / fertig werden","V","Ya terminé el trabajo.","Ich habe die Arbeit beendet."],
  ["acabar","beenden / gerade getan haben","V","Acabo de llegar.","Ich bin gerade angekommen."],
  ["comenzar","beginnen","V","La película va a comenzar.","Der Film fängt an."],
  ["parar","anhalten / aufhören","V","Para el coche.","Halt das Auto an."],
  ["seguir","weitermachen / folgen","V","Sigue recto.","Geh geradeaus weiter."],
  ["mover","bewegen","V","No puedo mover el brazo.","Ich kann den Arm nicht bewegen."],
  ["tocar","berühren / spielen (Instrument)","V","Sé tocar la guitarra.","Ich kann Gitarre spielen."],
  ["llorar","weinen","V","El bebé empezó a llorar.","Das Baby fing an zu weinen."],
  ["reír","lachen","V","Me haces reír.","Du bringst mich zum Lachen."],
  ["sonreír","lächeln","V","Ella sonríe siempre.","Sie lächelt immer."],
  ["gritar","schreien","V","No grites, por favor.","Schrei bitte nicht."],
  ["besar","küssen","V","La besó en la mejilla.","Er küsste sie auf die Wange."],
  ["abrazar","umarmen","V","Ven, te quiero abrazar.","Komm, ich will dich umarmen."],
  ["odiar","hassen","V","Odio esperar.","Ich hasse es zu warten."],
  ["amar","lieben","V","Te amo con locura.","Ich liebe dich wahnsinnig."],
  ["temer","fürchten","V","Temo lo peor.","Ich fürchte das Schlimmste."],
  ["preocupar","beunruhigen / sich sorgen","V","No te preocupes.","Mach dir keine Sorgen."],
  ["alegrar","erfreuen / sich freuen","V","Me alegro de verte.","Ich freue mich, dich zu sehen."],
  ["disfrutar","genießen","V","Disfruta la comida.","Genieß das Essen."],
  ["sufrir","leiden","V","No quiero que sufras.","Ich will nicht, dass du leidest."],
  ["descubrir","entdecken","V","Descubrí un lugar nuevo.","Ich habe einen neuen Ort entdeckt."],
  ["ocultar","verbergen / verstecken","V","No ocultes la verdad.","Verbirg die Wahrheit nicht."],
  ["mostrar","zeigen","V","Muéstrame el camino.","Zeig mir den Weg."],
  ["notar","bemerken","V","Noté que estabas triste.","Ich bemerkte, dass du traurig warst."],
  ["darse cuenta","merken / bemerken","V","Me di cuenta tarde.","Ich merkte es zu spät."],
  ["reconocer","erkennen / anerkennen","V","No te reconocí.","Ich habe dich nicht erkannt."],
  ["recordar","sich erinnern / erinnern an","V","Recuérdame llamarla.","Erinnere mich, sie anzurufen."],
  ["imaginar","sich vorstellen","V","Imagina un mundo mejor.","Stell dir eine bessere Welt vor."],
  ["suponer","annehmen / vermuten","V","Supongo que sí.","Ich nehme an, ja."],
  ["dudar","zweifeln","V","Lo dudo mucho.","Ich bezweifle es sehr."],
  ["creer","glauben","V","No lo puedo creer.","Ich kann es nicht glauben."],
  ["opinar","meinen / eine Meinung haben","V","¿Qué opinas tú?","Was meinst du?"],
  ["contestar","antworten","V","No contestó el teléfono.","Er ging nicht ans Telefon."],
  ["discutir","diskutieren / streiten","V","No quiero discutir.","Ich will nicht streiten."],
  ["gritar","rufen / schreien","V","Gritó de alegría.","Er schrie vor Freude."],
  ["cambiar","wechseln / ändern","V","Todo puede cambiar.","Alles kann sich ändern."],
  ["mejorar","verbessern","V","Quiero mejorar mi español.","Ich will mein Spanisch verbessern."],
  ["aumentar","erhöhen / steigen","V","Los precios aumentan.","Die Preise steigen."],
  ["bajar","senken / sinken","V","Bajó la temperatura.","Die Temperatur ist gesunken."],
  ["añadir","hinzufügen","V","Añade un poco de sal.","Füge etwas Salz hinzu."],
  ["quitar","wegnehmen / entfernen","V","Quita eso de ahí.","Nimm das da weg."],
  ["guardar","aufbewahren / speichern","V","Guarda el documento.","Speichere das Dokument."],
  ["llenar","füllen","V","Llena el vaso, por favor.","Füll das Glas, bitte."],
  ["vaciar","leeren","V","Voy a vaciar la maleta.","Ich leere den Koffer."],
  ["cortar","schneiden","V","Corta el pan.","Schneide das Brot."],
  ["pesar","wiegen","V","¿Cuánto pesas?","Wie viel wiegst du?"],
  ["medir","messen","V","Mide dos metros.","Er ist zwei Meter groß."],
  ["contar","zählen","V","Cuenta hasta diez.","Zähl bis zehn."],
  ["sumar","addieren","V","Suma estos números.","Addiere diese Zahlen."],
  ["valer","wert sein / kosten","V","¿Cuánto vale?","Wie viel kostet es?"],
  ["costar","kosten","V","Cuesta mucho dinero.","Es kostet viel Geld."],
  ["gastar","ausgeben","V","Gasté todo mi dinero.","Ich habe mein ganzes Geld ausgegeben."],
  ["ahorrar","sparen","V","Quiero ahorrar más.","Ich will mehr sparen."],
  ["deber","schulden","V","Te debo diez euros.","Ich schulde dir zehn Euro."],
  ["prestar","leihen (verleihen)","V","¿Me prestas un boli?","Leihst du mir einen Stift?"],
  ["devolver","zurückgeben","V","Devuélveme el libro.","Gib mir das Buch zurück."],
  ["romper","kaputtmachen","V","Rompí mi teléfono.","Ich habe mein Handy kaputt gemacht."],
  ["arreglar","reparieren / regeln","V","Voy a arreglar la bici.","Ich repariere das Fahrrad."],
  ["funcionar","funktionieren","V","No funciona el ascensor.","Der Aufzug funktioniert nicht."],
  ["encender","anmachen / einschalten","V","Enciende la luz.","Mach das Licht an."],
  ["apagar","ausmachen / ausschalten","V","Apaga la tele.","Mach den Fernseher aus."],
  ["esperar","warten","V","Espérame aquí.","Warte hier auf mich."],
  ["tardar","dauern / brauchen (Zeit)","V","¿Cuánto tardas?","Wie lange brauchst du?"],
  ["llegar","ankommen","V","El paquete llegó hoy.","Das Paket kam heute an."],
  ["partir","abfahren / aufbrechen","V","Partimos al amanecer.","Wir brechen im Morgengrauen auf."],
  ["regresar","zurückkehren","V","Regreso en una hora.","Ich komme in einer Stunde zurück."],
  ["quedarse","bleiben","V","Me quedo en casa.","Ich bleibe zu Hause."],
  ["marcharse","weggehen","V","Se marchó temprano.","Er ging früh weg."],
  ["acompañar","begleiten","V","Te acompaño a casa.","Ich begleite dich nach Hause."],
  ["invitar","einladen","V","Te invito a cenar.","Ich lade dich zum Abendessen ein."],
  ["visitar","besuchen","V","Voy a visitar a mi abuela.","Ich besuche meine Großmutter."],
  ["conocer","kennenlernen","V","Encantado de conocerte.","Schön, dich kennenzulernen."],
  ["presentar","vorstellen","V","Te presento a mi amigo.","Ich stelle dir meinen Freund vor."],
  ["saludar","grüßen / begrüßen","V","Salúdalo de mi parte.","Grüß ihn von mir."],
  ["despedirse","sich verabschieden","V","Se despidió con un abrazo.","Er verabschiedete sich mit einer Umarmung."],
  ["casarse","heiraten","V","Se casaron en junio.","Sie heirateten im Juni."],
  ["trabajar","arbeiten","V","Trabaja de camarero.","Er arbeitet als Kellner."],
  ["enseñar","lehren / zeigen","V","Me enseñó a nadar.","Sie brachte mir das Schwimmen bei."],
  ["aprender","lernen","V","Quiero aprender español.","Ich will Spanisch lernen."],
  ["practicar","üben / trainieren","V","Practico todos los días.","Ich übe jeden Tag."],
  ["estudiar","lernen / studieren","V","Estudio medicina.","Ich studiere Medizin."],
  ["leer","lesen","V","Leí un buen libro.","Ich habe ein gutes Buch gelesen."],
  ["escribir","schreiben","V","Escribo en mi diario.","Ich schreibe in mein Tagebuch."],
  ["contar","erzählen","V","Cuéntamelo todo.","Erzähl mir alles."],
  ["cantar","singen","V","Canta una canción.","Sing ein Lied."],
  ["dibujar","zeichnen","V","Me gusta dibujar.","Ich zeichne gern."],
  ["pintar","malen / streichen","V","Voy a pintar la pared.","Ich streiche die Wand."],
  ["nadar","schwimmen","V","No sé nadar.","Ich kann nicht schwimmen."],
  ["caminar","gehen / spazieren","V","Caminamos por la playa.","Wir gingen am Strand spazieren."],
  ["saltar","springen","V","El niño salta de alegría.","Das Kind springt vor Freude."],
  ["volar","fliegen","V","El avión vuela alto.","Das Flugzeug fliegt hoch."],
  ["conducir","fahren (lenken)","V","No sé conducir.","Ich kann nicht Auto fahren."],
  ["montar","reiten / aufsteigen","V","Voy a montar en bici.","Ich fahre Fahrrad."],
  ["ganar","verdienen","V","Gana mucho dinero.","Er verdient viel Geld."],
  ["perder","verpassen / verlieren","V","Perdí el tren.","Ich habe den Zug verpasst."],
  ["encontrar","finden","V","Encontré mis llaves.","Ich habe meine Schlüssel gefunden."],
  ["esconder","verstecken","V","Escondió el regalo.","Er versteckte das Geschenk."],
  ["seguir","weiterhin sein / bleiben","V","Sigo cansado.","Ich bin immer noch müde."]
];
