/* Frecuencia — deck expansion band D. Rows [es, de, pos]. Deduped at runtime. */
window.WORDS = (window.WORDS||[]).concat([
  // ---- leisure, sport, hobbies ----
  ["deporte","Sport","S(m)"],["fútbol","Fußball","S(m)"],["baloncesto","Basketball","S(m)"],
  ["tenis","Tennis","S(m)"],["natación","Schwimmen","S(f)"],["ciclismo","Radsport","S(m)"],
  ["carrera","Rennen / Lauf","S(f)"],["partido","Spiel (Sport)","S(m)"],["equipo","Mannschaft","S(m)"],
  ["jugador","Spieler","S(m)"],["entrenador","Trainer","S(m)"],["árbitro","Schiedsrichter","S(m)"],
  ["pelota","Ball","S(f)"],["balón","Ball (groß)","S(m)"],["gol","Tor","S(m)"],
  ["campo","Spielfeld / Feld","S(m)"],["cancha","Platz (Sport)","S(f)"],["gimnasio","Fitnessstudio","S(m)"],
  ["ejercicio","Übung / Sport","S(m)"],["entrenamiento","Training","S(m)"],["afición","Hobby / Anhängerschaft","S(f)"],
  ["pasatiempo","Zeitvertreib / Hobby","S(m)"],["juego","Spiel","S(m)"],["juguete","Spielzeug","S(m)"],
  ["carta","Spielkarte / Brief","S(f)"],["ajedrez","Schach","S(m)"],["baile","Tanz","S(m)"],
  ["fiesta","Fest / Party","S(f)"],["concierto","Konzert","S(m)"],["entrada","Eintrittskarte / Eingang","S(f)"],
  ["premio","Preis / Auszeichnung","S(m)"],["campeón","Meister / Champion","S(m)"],["victoria","Sieg","S(f)"],
  ["derrota","Niederlage","S(f)"],["empate","Unentschieden","S(m)"],
  // ---- arts & culture ----
  ["arte","Kunst","S(m)"],["cultura","Kultur","S(f)"],["música","Musik","S(f)"],
  ["canción","Lied","S(f)"],["cine","Kino / Film","S(m)"],["película","Film","S(f)"],
  ["obra","Werk / Theaterstück","S(f)"],["novela","Roman","S(f)"],["cuento","Erzählung / Märchen","S(m)"],
  ["poema","Gedicht","S(m)"],["poesía","Poesie / Dichtung","S(f)"],["pintura","Malerei / Gemälde","S(f)"],
  ["cuadro","Bild / Gemälde","S(m)"],["dibujo","Zeichnung","S(m)"],["foto","Foto","S(f)"],
  ["escultura","Skulptur","S(f)"],["instrumento","Instrument","S(m)"],["guitarra","Gitarre","S(f)"],
  ["piano","Klavier","S(m)"],["violín","Geige","S(m)"],["batería","Schlagzeug","S(f)"],
  ["voz","Stimme","S(f)"],["ritmo","Rhythmus","S(m)"],["escenario","Bühne","S(m)"],
  ["personaje","Figur / Charakter","S(m)"],["autor","Autor","S(m)"],["público","Publikum","S(m)"],
  ["historia","Geschichte","S(f)"],["leyenda","Legende","S(f)"],["mito","Mythos","S(m)"],
  ["tradición","Tradition","S(f)"],["costumbre","Sitte / Gewohnheit","S(f)"],["religión","Religion","S(f)"],
  // ---- science & abstract ----
  ["ciencia","Wissenschaft","S(f)"],["conocimiento","Wissen","S(m)"],["investigación","Forschung","S(f)"],
  ["experimento","Experiment","S(m)"],["teoría","Theorie","S(f)"],["prueba","Beweis / Test","S(f)"],
  ["resultado","Ergebnis","S(m)"],["causa","Ursache","S(f)"],["consecuencia","Folge","S(f)"],
  ["efecto","Wirkung / Effekt","S(m)"],["razón","Grund / Vernunft","S(f)"],["motivo","Motiv / Anlass","S(m)"],
  ["objetivo","Ziel","S(m)"],["meta","Ziel","S(f)"],["propósito","Absicht / Zweck","S(m)"],
  ["ventaja","Vorteil","S(f)"],["desventaja","Nachteil","S(f)"],["beneficio","Nutzen / Gewinn","S(m)"],
  ["riesgo","Risiko","S(m)"],["peligro","Gefahr","S(m)"],["seguridad","Sicherheit","S(f)"],
  ["libertad","Freiheit","S(f)"],["igualdad","Gleichheit","S(f)"],["justicia","Gerechtigkeit","S(f)"],
  ["poder","Macht","S(m)"],["fuerza","Kraft","S(f)"],["energía","Energie","S(f)"],
  ["esfuerzo","Anstrengung","S(m)"],["capacidad","Fähigkeit / Kapazität","S(f)"],["habilidad","Geschick","S(f)"],
  ["talento","Talent","S(m)"],["experiencia","Erfahrung","S(f)"],["costumbre","Gewohnheit","S(f)"],
  ["hábito","Gewohnheit","S(m)"],["opinión","Meinung","S(f)"],["idea","Idee","S(f)"],
  ["pensamiento","Gedanke","S(m)"],["duda","Zweifel","S(f)"],["decisión","Entscheidung","S(f)"],
  ["elección","Wahl","S(f)"],["oportunidad","Gelegenheit / Chance","S(f)"],["posibilidad","Möglichkeit","S(f)"],
  ["realidad","Wirklichkeit","S(f)"],["situación","Situation / Lage","S(f)"],["condición","Bedingung / Zustand","S(f)"],
  ["relación","Beziehung","S(f)"],["diferencia","Unterschied","S(f)"],["semejanza","Ähnlichkeit","S(f)"],
  ["comparación","Vergleich","S(f)"],["ejemplo","Beispiel","S(m)"],["detalle","Detail / Einzelheit","S(m)"],
  ["aspecto","Aspekt / Aussehen","S(m)"],["cualidad","Eigenschaft","S(f)"],["defecto","Mangel / Fehler","S(m)"],
  ["valor","Wert / Mut","S(m)"],["sentido","Sinn / Bedeutung","S(m)"],["significado","Bedeutung","S(m)"],
  ["misterio","Geheimnis / Rätsel","S(m)"],["secreto","Geheimnis","S(m)"],["sorpresa","Überraschung","S(f)"],
  // ---- materials & objects ----
  ["material","Material","S(m)"],["madera","Holz","S(f)"],["metal","Metall","S(m)"],
  ["hierro","Eisen","S(m)"],["acero","Stahl","S(m)"],["oro","Gold","S(m)"],
  ["plata","Silber","S(f)"],["cobre","Kupfer","S(m)"],["plástico","Plastik","S(m)"],
  ["vidrio","Glas (Material)","S(m)"],["cristal","Kristall / Glas","S(m)"],["papel","Papier","S(m)"],
  ["cartón","Karton / Pappe","S(m)"],["tela","Stoff","S(f)"],["algodón","Baumwolle","S(m)"],
  ["lana","Wolle","S(f)"],["cuero","Leder","S(m)"],["goma","Gummi","S(f)"],
  ["cemento","Zement","S(m)"],["ladrillo","Ziegel","S(m)"],["polvo","Staub / Pulver","S(m)"],
  ["barro","Lehm / Schlamm","S(m)"],["objeto","Gegenstand","S(m)"],["cosa","Ding","S(f)"],
  ["herramienta","Werkzeug","S(f)"],["máquina","Maschine","S(f)"],["motor","Motor","S(m)"],
  ["clavo","Nagel","S(m)"],["tornillo","Schraube","S(m)"],["martillo","Hammer","S(m)"],
  ["cadena","Kette","S(f)"],["cuerda","Seil / Schnur","S(f)"],["hilo","Faden","S(m)"],
  ["aguja","Nadel","S(f)"],["bolsa","Beutel / Tüte","S(f)"],["caja","Schachtel / Kiste","S(f)"],
  ["paquete","Paket","S(m)"],["tapa","Deckel","S(f)"],["saco","Sack","S(m)"],
  ["rueda","Rad","S(f)"],["palo","Stock / Stab","S(m)"],["tabla","Brett / Tabelle","S(f)"],
  // ---- quantities & measures ----
  ["cantidad","Menge","S(f)"],["número","Zahl / Nummer","S(m)"],["cifra","Zahl / Ziffer","S(f)"],
  ["total","Gesamtsumme","S(m)"],["suma","Summe","S(f)"],["resto","Rest","S(m)"],
  ["parte","Teil","S(f)"],["trozo","Stück","S(m)"],["pedazo","Stück / Brocken","S(m)"],
  ["montón","Haufen / Menge","S(m)"],["grupo","Gruppe","S(m)"],["conjunto","Menge / Gesamtheit","S(m)"],
  ["fila","Reihe","S(f)"],["línea","Linie / Zeile","S(f)"],["punto","Punkt","S(m)"],
  ["metro","Meter","S(m)"],["centímetro","Zentimeter","S(m)"],["kilómetro","Kilometer","S(m)"],
  ["litro","Liter","S(m)"],["kilo","Kilo","S(m)"],["gramo","Gramm","S(m)"],
  ["grado","Grad","S(m)"],["peso","Gewicht","S(m)"],["altura","Höhe","S(f)"],
  ["anchura","Breite","S(f)"],["longitud","Länge","S(f)"],["profundidad","Tiefe","S(f)"],
  ["tamaño","Größe","S(m)"],["velocidad","Geschwindigkeit","S(f)"],["distancia","Entfernung","S(f)"],
  ["mayoría","Mehrheit","S(f)"],["minoría","Minderheit","S(f)"],["media","Durchschnitt","S(f)"],
  ["doble","das Doppelte","S(m)"],["triple","das Dreifache","S(m)"],
  // ---- weather & environment ----
  ["clima","Klima","S(m)"],["tiempo","Wetter","S(m)"],["temperatura","Temperatur","S(f)"],
  ["tormenta","Sturm / Gewitter","S(f)"],["trueno","Donner","S(m)"],["relámpago","Blitz","S(m)"],
  ["niebla","Nebel","S(f)"],["nube","Wolke","S(f)"],["cielo","Himmel","S(m)"],
  ["sombra","Schatten","S(f)"],["arcoíris","Regenbogen","S(m)"],["helada","Frost","S(f)"],
  ["ola de calor","Hitzewelle","S(f)"],["sequía","Dürre","S(f)"],["inundación","Überschwemmung","S(f)"],
  ["terremoto","Erdbeben","S(m)"],["incendio","Brand","S(m)"],["contaminación","Verschmutzung","S(f)"],
  ["medio ambiente","Umwelt","S(m)"],["energía","Energie","S(f)"],["basura","Abfall","S(f)"],
  // ---- communication & cognition verbs ----
  ["comunicar","mitteilen","V"],["informar","informieren","V"],["avisar","benachrichtigen / warnen","V"],
  ["advertir","warnen / hinweisen","V"],["anunciar","ankündigen","V"],["declarar","erklären / angeben","V"],
  ["mencionar","erwähnen","V"],["comentar","kommentieren / bemerken","V"],["charlar","plaudern","V"],
  ["conversar","sich unterhalten","V"],["discutir","diskutieren / streiten","V"],["negociar","verhandeln","V"],
  ["acordar","vereinbaren","V"],["prometer","versprechen","V"],["jurar","schwören","V"],
  ["mentir","lügen","V"],["engañar","täuschen / betrügen","V"],["convencer","überzeugen","V"],
  ["insistir","beharren / bestehen","V"],["rogar","bitten / flehen","V"],["pedir","bitten / bestellen","V"],
  ["agradecer","danken","V"],["felicitar","gratulieren","V"],["saludar","grüßen","V"],
  ["presentar","vorstellen","V"],["despedir","verabschieden / entlassen","V"],["gritar","schreien","V"],
  ["susurrar","flüstern","V"],["pensar","denken","V"],["reflexionar","nachdenken","V"],
  ["razonar","argumentieren / denken","V"],["opinar","meinen","V"],["suponer","annehmen","V"],
  ["imaginar","sich vorstellen","V"],["adivinar","erraten","V"],["planear","planen","V"],
  ["decidir","entscheiden","V"],["dudar","zweifeln","V"],["confiar","vertrauen","V"],
  ["desconfiar","misstrauen","V"],["comparar","vergleichen","V"],["analizar","analysieren","V"],
  ["examinar","untersuchen","V"],["revisar","überprüfen","V"],["calcular","berechnen","V"],
  ["contar","zählen / erzählen","V"],["medir","messen","V"],["pesar","wiegen","V"],
  ["resolver","lösen","V"],["solucionar","lösen","V"],["aclarar","klären / aufhellen","V"],
  ["explicar","erklären","V"],["enseñar","lehren / zeigen","V"],["aprender","lernen","V"],
  ["memorizar","auswendig lernen","V"],["repasar","wiederholen / durchgehen","V"],["practicar","üben","V"],
  // ---- movement & position verbs ----
  ["acercarse","sich nähern","V"],["alejarse","sich entfernen","V"],["cruzar","überqueren","V"],
  ["atravesar","durchqueren","V"],["rodear","umgeben / umkreisen","V"],["seguir","folgen","V"],
  ["perseguir","verfolgen","V"],["escapar","entkommen / fliehen","V"],["huir","fliehen","V"],
  ["esconderse","sich verstecken","V"],["asomarse","hinausschauen / sich zeigen","V"],["aparecer","erscheinen","V"],
  ["colgar","aufhängen","V"],["colocar","platzieren","V"],["situar","platzieren / verorten","V"],
  ["apoyar","stützen / unterstützen","V"],["inclinar","neigen","V"],["arrodillarse","niederknien","V"],
  ["agacharse","sich bücken","V"],["tumbarse","sich hinlegen","V"],["estirarse","sich strecken","V"],
  // ---- discourse / useful phrases ----
  ["por favor","bitte","Interj"],["de nada","gern geschehen","Interj"],["lo siento","es tut mir leid","Interj"],
  ["con permiso","mit Verlaub / Entschuldigung","Interj"],["buenos días","guten Morgen","Interj"],["buenas tardes","guten Tag (nachmittags)","Interj"],
  ["buenas noches","gute Nacht","Interj"],["hasta luego","bis später","Interj"],["bienvenido","willkommen","Interj"],
  ["felicidades","herzlichen Glückwunsch","Interj"],["buen provecho","guten Appetit","Interj"],["salud","Gesundheit / Prost","Interj"],
  ["a lo mejor","womöglich","Adv"],["ni idea","keine Ahnung","Interj"],["por supuesto","selbstverständlich","Interj"],
  ["está bien","in Ordnung / okay","Interj"],["de acuerdo","einverstanden","Interj"],["ya veo","ich verstehe","Interj"],
  ["¿verdad?","nicht wahr?","Interj"],["¿de verdad?","wirklich?","Interj"],["a ver","mal sehen","Interj"],
  ["depende","kommt darauf an","Interj"],["más o menos","mehr oder weniger","Adv"],["poco a poco","nach und nach","Adv"],
  ["en fin","na ja / kurzum","Interj"],["o sea","das heißt / also","Interj"],["por cierto","übrigens","Adv"]
]);
