/* Frecuencia — deck expansion band F (final fill past 2000). Rows [es, de, pos]. Deduped at runtime. */
window.WORDS = (window.WORDS||[]).concat([
  ["comienzo","Anfang / Beginn","S(m)"],["origen","Ursprung / Herkunft","S(m)"],["destino","Schicksal / Ziel","S(m)"],
  ["suerte","Glück / Schicksal","S(f)"],["azar","Zufall","S(m)"],["ocasión","Gelegenheit / Anlass","S(f)"],
  ["acontecimiento","Ereignis","S(m)"],["suceso","Vorfall / Ereignis","S(m)"],["hecho","Tatsache","S(m)"],
  ["escena","Szene","S(f)"],["imagen","Bild","S(f)"],["figura","Figur / Gestalt","S(f)"],
  ["forma","Form","S(f)"],["modelo","Modell / Vorbild","S(m)"],["estilo","Stil","S(m)"],
  ["moda","Mode","S(f)"],["gusto","Geschmack / Vorliebe","S(m)"],["interés","Interesse","S(m)"],
  ["atención","Aufmerksamkeit","S(f)"],["curiosidad","Neugier","S(f)"],["ganas","Lust","S(f)"],
  ["deseo","Wunsch / Verlangen","S(m)"],["voluntad","Wille","S(f)"],["intención","Absicht","S(f)"],
  ["actitud","Haltung / Einstellung","S(f)"],["comportamiento","Verhalten","S(m)"],["carácter","Charakter","S(m)"],
  ["personalidad","Persönlichkeit","S(f)"],["estado de ánimo","Gemütszustand","S(m)"],["humor","Laune / Humor","S(m)"],
  ["emoción","Gefühl / Emotion","S(f)"],["sentimiento","Gefühl","S(m)"],["sensación","Empfindung / Gefühl","S(f)"],
  ["placer","Vergnügen / Freude","S(m)"],["dolor","Leid / Schmerz","S(m)"],["sufrimiento","Leiden","S(m)"],
  ["felicidad","Glück / Zufriedenheit","S(f)"],["tristeza","Traurigkeit","S(f)"],["soledad","Einsamkeit","S(f)"],
  ["compañía","Gesellschaft / Firma","S(f)"],["amistad","Freundschaft","S(f)"],["confianza","Vertrauen","S(f)"],
  ["respeto","Respekt","S(m)"],["admiración","Bewunderung","S(f)"],["gratitud","Dankbarkeit","S(f)"],
  ["orgullo","Stolz","S(m)"],["envidia","Neid","S(f)"],["rabia","Wut","S(f)"],
  ["ira","Zorn","S(f)"],["temor","Furcht","S(m)"],["pánico","Panik","S(m)"],
  ["ansiedad","Angst / Unruhe","S(f)"],["estrés","Stress","S(m)"],["calma","Ruhe","S(f)"],
  ["paciencia","Geduld","S(f)"],["prisa","Eile","S(f)"],["descanso","Erholung / Pause","S(m)"],
  // more verbs (mixed frequency, useful)
  ["aprovechar","nutzen / ausnutzen","V"],["disfrutar","genießen","V"],["merecer","verdienen","V"],
  ["soñar","träumen","V"],["desear","wünschen","V"],["esperar","hoffen / warten","V"],
  ["temer","fürchten","V"],["preocuparse","sich sorgen","V"],["alegrarse","sich freuen","V"],
  ["sorprender","überraschen","V"],["molestar","stören / belästigen","V"],["fastidiar","ärgern / nerven","V"],
  ["agradar","gefallen","V"],["encantar","begeistern / sehr gefallen","V"],["odiar","hassen","V"],
  ["soportar","ertragen / aushalten","V"],["aguantar","aushalten","V"],["acostumbrar","gewöhnen","V"],
  ["recordar","erinnern","V"],["olvidar","vergessen","V"],["confundir","verwechseln / verwirren","V"],
  ["darse cuenta","bemerken","V"],["enterarse","erfahren","V"],["averiguar","herausfinden","V"],
  ["comprobar","überprüfen","V"],["asegurarse","sich vergewissern","V"],["arriesgarse","ein Risiko eingehen","V"],
  ["esforzarse","sich bemühen","V"],["lograr","erreichen","V"],["fracasar","scheitern","V"],
  ["celebrar","feiern","V"],["organizar","organisieren","V"],["participar","teilnehmen","V"],
  ["colaborar","mitarbeiten","V"],["ayudar","helfen","V"],["servir","dienen / servieren","V"],
  ["atender","bedienen / sich kümmern","V"],["acompañar","begleiten","V"],["dirigirse","sich wenden / hingehen","V"],
  ["saludar","begrüßen","V"],["comportarse","sich verhalten","V"],["portarse","sich benehmen","V"],
  ["tratar","behandeln","V"],["respetar","respektieren","V"],["admirar","bewundern","V"],
  ["envidiar","beneiden","V"],["confiar","vertrauen","V"],["fiarse","sich verlassen auf","V"],
  ["mentir","lügen","V"],["engañar","betrügen","V"],["traicionar","verraten","V"],
  ["defender","verteidigen","V"],["proteger","schützen","V"],["amenazar","bedrohen","V"],
  ["asustar","erschrecken","V"],["animar","ermutigen","V"],["consolar","trösten","V"],
  ["felicitar","gratulieren","V"],["disculparse","sich entschuldigen","V"],["agradecer","danken","V"],
  // misc common nouns
  ["luz","Licht","S(f)"],["sombra","Schatten","S(f)"],["fuego","Feuer","S(m)"],
  ["humo","Rauch","S(m)"],["ceniza","Asche","S(f)"],["chispa","Funke","S(f)"],
  ["gota","Tropfen","S(f)"],["charco","Pfütze","S(m)"],["corriente","Strömung / Strom","S(f)"],
  ["orilla","Ufer","S(f)"],["camino","Weg","S(m)"],["sendero","Pfad","S(m)"],
  ["huella","Spur / Fußabdruck","S(f)"],["señal","Zeichen / Signal","S(f)"],["marca","Marke / Zeichen","S(f)"],
  ["mancha","Fleck","S(f)"],["arruga","Falte","S(f)"],["nudo","Knoten","S(m)"],
  ["montón","Haufen","S(m)"],["pila","Stapel / Batterie","S(f)"],["pareja","Paar / Partner","S(f)"],
  ["turno","Schicht / Reihe (dran sein)","S(m)"],["cola","Schlange (Warteschlange) / Schwanz","S(f)"],["fila","Reihe / Schlange","S(f)"]
]);
