/* Frecuencia — deck expansion band B (common vocabulary, rank ~670+).
   Rows [es, de, pos]; example sentences omitted here (added in vetted batches).
   Deduped at runtime against band A. */
window.WORDS = (window.WORDS||[]).concat([
  // ---- more high-frequency verbs ----
  ["deber","müssen / sollen","V"],["soler","pflegen zu / meist tun","V"],["faltar","fehlen","V"],
  ["quedar","übrig bleiben / verabreden","V"],["tratar","behandeln / versuchen","V"],["dejar","lassen","V"],
  ["llevar","tragen / mitnehmen","V"],["pasar","vorbeigehen / geschehen","V"],["seguir","folgen","V"],
  ["poner","stellen / legen","V"],["parecer","scheinen","V"],["quedarse","bleiben","V"],
  ["convertir","verwandeln / umwandeln","V"],["conseguir","erreichen","V"],["mantener","behalten / halten","V"],
  ["aparecer","erscheinen / auftauchen","V"],["considerar","betrachten / erwägen","V"],["permitir","erlauben","V"],
  ["realizar","durchführen / verwirklichen","V"],["presentar","vorstellen / präsentieren","V"],["ofrecer","anbieten","V"],
  ["señalar","zeigen / hinweisen","V"],["indicar","angeben / hinweisen","V"],["asegurar","versichern","V"],
  ["establecer","festlegen / gründen","V"],["desarrollar","entwickeln","V"],["formar","bilden / formen","V"],
  ["producir","produzieren","V"],["representar","darstellen / vertreten","V"],["comprender","verstehen / umfassen","V"],
  ["obtener","erhalten / bekommen","V"],["dirigir","leiten / lenken","V"],["disponer","verfügen / anordnen","V"],
  ["referir","sich beziehen / berichten","V"],["expresar","ausdrücken","V"],["reunir","versammeln / vereinen","V"],
  ["actuar","handeln / agieren","V"],["participar","teilnehmen","V"],["colocar","platzieren / hinstellen","V"],
  ["alcanzar","erreichen / einholen","V"],["evitar","vermeiden","V"],["marcar","markieren / wählen","V"],
  ["comprobar","überprüfen / feststellen","V"],["observar","beobachten","V"],["reconocer","erkennen / anerkennen","V"],
  ["defender","verteidigen","V"],["atacar","angreifen","V"],["luchar","kämpfen","V"],
  ["ganar","gewinnen / verdienen","V"],["salvar","retten","V"],["proteger","schützen","V"],
  ["arriesgar","riskieren","V"],["provocar","provozieren / verursachen","V"],["causar","verursachen","V"],
  ["impedir","verhindern","V"],["obligar","zwingen","V"],["exigir","fordern / verlangen","V"],
  ["merecer","verdienen (wert sein)","V"],["pertenecer","gehören / angehören","V"],["depender","abhängen","V"],
  ["influir","beeinflussen","V"],["afectar","betreffen / beeinträchtigen","V"],["provenir","stammen / herkommen","V"],
  ["surgir","entstehen / aufkommen","V"],["desaparecer","verschwinden","V"],["fallar","versagen / scheitern","V"],
  ["acertar","richtig raten / treffen","V"],["fracasar","scheitern","V"],["triunfar","triumphieren","V"],
  ["superar","überwinden / übertreffen","V"],["dominar","beherrschen","V"],["controlar","kontrollieren / steuern","V"],
  ["organizar","organisieren","V"],["planear","planen","V"],["preparar","vorbereiten","V"],
  ["cocinar","kochen","V"],["hornear","backen","V"],["freír","braten / frittieren","V"],
  ["hervir","kochen (Flüssigkeit)","V"],["probar","probieren / testen","V"],["masticar","kauen","V"],
  ["tragar","schlucken","V"],["morder","beißen","V"],["oler","riechen","V"],
  ["tocar","berühren / anfassen","V"],["agarrar","greifen / packen","V"],["soltar","loslassen","V"],
  ["empujar","schieben / stoßen","V"],["tirar","werfen / ziehen","V"],["lanzar","werfen / starten","V"],
  ["recoger","aufheben / abholen","V"],["levantar","hochheben","V"],["cargar","laden / tragen","V"],
  ["arrastrar","schleppen / ziehen","V"],["girar","drehen / abbiegen","V"],["doblar","biegen / falten","V"],
  ["estirar","strecken / dehnen","V"],["apretar","drücken / anziehen","V"],["golpear","schlagen","V"],
  ["romper","zerbrechen","V"],["cortar","schneiden","V"],["pegar","kleben / schlagen","V"],
  ["atar","binden","V"],["desatar","losbinden","V"],["coser","nähen","V"],
  ["arreglar","reparieren / regeln","V"],["reparar","reparieren","V"],["construir","bauen","V"],
  ["destruir","zerstören","V"],["fabricar","herstellen","V"],["diseñar","entwerfen / gestalten","V"],
  // ---- reflexive / daily-routine verbs ----
  ["ducharse","duschen","V"],["bañarse","baden","V"],["peinarse","sich kämmen","V"],
  ["vestirse","sich anziehen","V"],["desnudarse","sich ausziehen","V"],["afeitarse","sich rasieren","V"],
  ["maquillarse","sich schminken","V"],["acostarse","sich hinlegen / ins Bett gehen","V"],["dormirse","einschlafen","V"],
  ["cepillarse","sich putzen (Zähne)","V"],["secarse","sich abtrocknen","V"],["sentarse","sich setzen","V"],
  ["moverse","sich bewegen","V"],["caerse","hinfallen","V"],["cansarse","müde werden","V"],
  ["aburrirse","sich langweilen","V"],["divertirse","sich amüsieren","V"],["enfadarse","sich ärgern","V"],
  ["enojarse","wütend werden","V"],["asustarse","erschrecken","V"],["sorprenderse","sich wundern","V"],
  ["preocuparse","sich sorgen","V"],["quejarse","sich beschweren","V"],["reírse","lachen","V"],
  ["callarse","still sein / schweigen","V"],["equivocarse","sich irren","V"],["darse prisa","sich beeilen","V"],
  ["acordarse","sich erinnern","V"],["olvidarse","vergessen","V"],["fijarse","aufpassen / bemerken","V"],
  ["atreverse","sich trauen","V"],["negarse","sich weigern","V"],["esforzarse","sich anstrengen","V"],
  ["acostumbrarse","sich gewöhnen","V"],["mudarse","umziehen","V"],["jubilarse","in Rente gehen","V"],
  // ---- people, family, professions ----
  ["persona","Person","S(f)"],["ser humano","Mensch","S(m)"],["adulto","Erwachsener","S(m)"],
  ["bebé","Baby","S(m)"],["joven","junger Mensch","S(m)"],["anciano","alter Mensch","S(m)"],
  ["vecino","Nachbar","S(m)"],["invitado","Gast","S(m)"],["desconocido","Fremder","S(m)"],
  ["pareja","Partner / Paar","S(f)"],["novio","Freund (Partner)","S(m)"],["novia","Freundin (Partnerin)","S(f)"],
  ["tío","Onkel","S(m)"],["tía","Tante","S(f)"],["primo","Cousin","S(m)"],
  ["sobrino","Neffe","S(m)"],["nieto","Enkel","S(m)"],["suegra","Schwiegermutter","S(f)"],
  ["cuñado","Schwager","S(m)"],["yerno","Schwiegersohn","S(m)"],["gemelo","Zwilling","S(m)"],
  ["jefe","Chef","S(m)"],["colega","Kollege","S(m)"],["cliente","Kunde","S(m)"],
  ["profesor","Lehrer","S(m)"],["maestro","Lehrer / Meister","S(m)"],["estudiante","Student / Schüler","S(m)"],
  ["alumno","Schüler","S(m)"],["médico","Arzt","S(m)"],["enfermero","Krankenpfleger","S(m)"],
  ["dentista","Zahnarzt","S(m)"],["abogado","Anwalt","S(m)"],["juez","Richter","S(m)"],
  ["policía","Polizist","S(m)"],["bombero","Feuerwehrmann","S(m)"],["soldado","Soldat","S(m)"],
  ["ingeniero","Ingenieur","S(m)"],["arquitecto","Architekt","S(m)"],["científico","Wissenschaftler","S(m)"],
  ["programador","Programmierer","S(m)"],["periodista","Journalist","S(m)"],["escritor","Schriftsteller","S(m)"],
  ["artista","Künstler","S(m)"],["actor","Schauspieler","S(m)"],["cantante","Sänger","S(m)"],
  ["músico","Musiker","S(m)"],["pintor","Maler","S(m)"],["cocinero","Koch","S(m)"],
  ["camarero","Kellner","S(m)"],["panadero","Bäcker","S(m)"],["agricultor","Landwirt","S(m)"],
  ["conductor","Fahrer","S(m)"],["piloto","Pilot","S(m)"],["vendedor","Verkäufer","S(m)"],
  ["dependiente","Verkäufer / Angestellter","S(m)"],["empleado","Angestellter","S(m)"],["director","Direktor / Leiter","S(m)"],
  ["presidente","Präsident","S(m)"],["rey","König","S(m)"],["reina","Königin","S(m)"],
  ["equipo","Team / Mannschaft","S(m)"],["socio","Partner / Teilhaber","S(m)"],
  // ---- body & health ----
  ["cabello","Haar","S(m)"],["frente","Stirn","S(f)"],["ceja","Augenbraue","S(f)"],
  ["pestaña","Wimper","S(f)"],["mejilla","Wange","S(f)"],["nariz","Nase","S(f)"],
  ["oreja","Ohr","S(f)"],["oído","Gehör / inneres Ohr","S(m)"],["labio","Lippe","S(m)"],
  ["lengua","Zunge / Sprache","S(f)"],["garganta","Hals / Kehle","S(f)"],["cuello","Hals / Nacken","S(m)"],
  ["hombro","Schulter","S(m)"],["codo","Ellbogen","S(m)"],["muñeca","Handgelenk / Puppe","S(f)"],
  ["dedo","Finger / Zeh","S(m)"],["uña","Nagel","S(f)"],["pecho","Brust","S(m)"],
  ["espalda","Rücken","S(f)"],["cintura","Taille","S(f)"],["cadera","Hüfte","S(f)"],
  ["pierna","Bein","S(f)"],["rodilla","Knie","S(f)"],["tobillo","Knöchel","S(m)"],
  ["talón","Ferse","S(m)"],["piel","Haut","S(f)"],["hueso","Knochen","S(m)"],
  ["músculo","Muskel","S(m)"],["cerebro","Gehirn","S(m)"],["pulmón","Lunge","S(m)"],
  ["estómago","Magen","S(m)"],["hígado","Leber","S(m)"],["riñón","Niere","S(m)"],
  ["salud","Gesundheit","S(f)"],["enfermedad","Krankheit","S(f)"],["fiebre","Fieber","S(f)"],
  ["gripe","Grippe","S(f)"],["resfriado","Erkältung","S(m)"],["tos","Husten","S(f)"],
  ["herida","Wunde / Verletzung","S(f)"],["dolor","Schmerz","S(m)"],["medicina","Medizin / Medikament","S(f)"],
  ["pastilla","Tablette","S(f)"],["receta","Rezept","S(f)"],["cita","Termin / Verabredung","S(f)"],
  ["farmacia","Apotheke","S(f)"],["cansancio","Müdigkeit","S(m)"],["descanso","Ruhe / Pause","S(m)"],
  // ---- food & kitchen ----
  ["desayuno","Frühstück","S(m)"],["almuerzo","Mittagessen","S(m)"],["cena","Abendessen","S(f)"],
  ["merienda","Zwischenmahlzeit / Vesper","S(f)"],["plato","Teller / Gericht","S(m)"],["vaso","Glas / Becher","S(m)"],
  ["taza","Tasse","S(f)"],["copa","Glas (Stiel) / Pokal","S(f)"],["botella","Flasche","S(f)"],
  ["cuchara","Löffel","S(f)"],["tenedor","Gabel","S(m)"],["cuchillo","Messer","S(m)"],
  ["servilleta","Serviette","S(f)"],["mantel","Tischdecke","S(m)"],["olla","Topf","S(f)"],
  ["sartén","Pfanne","S(f)"],["horno","Ofen","S(m)"],["nevera","Kühlschrank","S(f)"],
  ["harina","Mehl","S(f)"],["aceite","Öl","S(m)"],["vinagre","Essig","S(m)"],
  ["mantequilla","Butter","S(f)"],["mermelada","Marmelade","S(f)"],["miel","Honig","S(f)"],
  ["galleta","Keks","S(f)"],["pastel","Kuchen","S(m)"],["tarta","Torte","S(f)"],
  ["helado","Eis","S(m)"],["chocolate","Schokolade","S(m)"],["dulce","Süßigkeit / süß","S(m)"],
  ["sopa","Suppe","S(f)"],["ensalada","Salat","S(f)"],["bocadillo","belegtes Brötchen","S(m)"],
  ["jamón","Schinken","S(m)"],["pescado","Fisch (Speise)","S(m)"],["marisco","Meeresfrüchte","S(m)"],
  ["patata","Kartoffel","S(f)"],["tomate","Tomate","S(m)"],["cebolla","Zwiebel","S(f)"],
  ["ajo","Knoblauch","S(m)"],["zanahoria","Karotte","S(f)"],["lechuga","Kopfsalat","S(f)"],
  ["pimiento","Paprika","S(m)"],["seta","Pilz","S(f)"],["limón","Zitrone","S(m)"],
  ["fresa","Erdbeere","S(f)"],["plátano","Banane","S(m)"],["uva","Traube","S(f)"],
  ["pera","Birne","S(f)"],["melocotón","Pfirsich","S(m)"],["sandía","Wassermelone","S(f)"],
  ["zumo","Saft","S(m)"],["refresco","Erfrischungsgetränk","S(m)"],["hielo","Eis (gefroren)","S(m)"],
  ["sabor","Geschmack","S(m)"],["hambre","Hunger","S(f)"],["sed","Durst","S(f)"],
  ["receta","Rezept (Küche)","S(f)"],["ingrediente","Zutat","S(m)"],
  // ---- house & furniture ----
  ["hogar","Zuhause / Heim","S(m)"],["piso","Wohnung / Stockwerk","S(m)"],["apartamento","Wohnung","S(m)"],
  ["salón","Wohnzimmer","S(m)"],["comedor","Esszimmer","S(m)"],["dormitorio","Schlafzimmer","S(m)"],
  ["pasillo","Flur","S(m)"],["escalera","Treppe","S(f)"],["ascensor","Aufzug","S(m)"],
  ["techo","Decke / Dach","S(m)"],["suelo","Boden","S(m)"],["pared","Wand","S(f)"],
  ["muro","Mauer","S(m)"],["ventana","Fenster","S(f)"],["balcón","Balkon","S(m)"],
  ["mueble","Möbelstück","S(m)"],["sofá","Sofa","S(m)"],["sillón","Sessel","S(m)"],
  ["armario","Schrank","S(m)"],["cajón","Schublade","S(m)"],["estantería","Regal","S(f)"],
  ["lámpara","Lampe","S(f)"],["espejo","Spiegel","S(m)"],["alfombra","Teppich","S(f)"],
  ["cortina","Vorhang","S(f)"],["almohada","Kissen","S(f)"],["manta","Decke","S(f)"],
  ["sábana","Bettlaken","S(f)"],["toalla","Handtuch","S(f)"],["jabón","Seife","S(m)"],
  ["cepillo","Bürste","S(m)"],["llave","Schlüssel","S(f)"],["cerradura","Schloss","S(f)"],
  ["enchufe","Steckdose / Stecker","S(m)"],["basura","Müll","S(f)"],["cubo","Eimer","S(m)"],
  // ---- clothing ----
  ["ropa","Kleidung","S(f)"],["camiseta","T-Shirt","S(f)"],["jersey","Pullover","S(m)"],
  ["abrigo","Mantel","S(m)"],["chaqueta","Jacke","S(f)"],["falda","Rock","S(f)"],
  ["vestido","Kleid","S(m)"],["traje","Anzug","S(m)"],["corbata","Krawatte","S(f)"],
  ["calcetín","Socke","S(m)"],["zapatilla","Hausschuh / Turnschuh","S(f)"],["bota","Stiefel","S(f)"],
  ["guante","Handschuh","S(m)"],["bufanda","Schal","S(f)"],["gorra","Mütze / Kappe","S(f)"],
  ["gafas","Brille","S(f)"],["bolso","Handtasche","S(m)"],["cartera","Geldbörse","S(f)"],
  ["mochila","Rucksack","S(f)"],["cinturón","Gürtel","S(m)"],["anillo","Ring","S(m)"],
  ["collar","Halskette","S(m)"],["talla","Kleidergröße","S(f)"],["moda","Mode","S(f)"],
  // ---- nature & animals ----
  ["naturaleza","Natur","S(f)"],["tierra","Erde / Land","S(f)"],["mundo","Welt","S(m)"],
  ["planeta","Planet","S(m)"],["estrella","Stern","S(f)"],["universo","Universum","S(m)"],
  ["montaña","Berg","S(f)"],["colina","Hügel","S(f)"],["valle","Tal","S(m)"],
  ["llanura","Ebene","S(f)"],["desierto","Wüste","S(m)"],["selva","Dschungel","S(f)"],
  ["lago","See","S(m)"],["océano","Ozean","S(m)"],["ola","Welle","S(f)"],
  ["costa","Küste","S(f)"],["arena","Sand","S(f)"],["roca","Fels","S(f)"],
  ["piedra","Stein","S(f)"],["hoja","Blatt","S(f)"],["rama","Ast","S(f)"],
  ["raíz","Wurzel","S(f)"],["semilla","Samen","S(f)"],["hierba","Gras / Kraut","S(f)"],
  ["planta","Pflanze","S(f)"],["animal","Tier","S(m)"],["mascota","Haustier","S(f)"],
  ["vaca","Kuh","S(f)"],["toro","Stier","S(m)"],["oveja","Schaf","S(f)"],
  ["cabra","Ziege","S(f)"],["cerdo","Schwein","S(m)"],["gallina","Henne","S(f)"],
  ["gallo","Hahn","S(m)"],["pato","Ente","S(m)"],["conejo","Kaninchen","S(m)"],
  ["ratón","Maus","S(m)"],["león","Löwe","S(m)"],["tigre","Tiger","S(m)"],
  ["oso","Bär","S(m)"],["lobo","Wolf","S(m)"],["zorro","Fuchs","S(m)"],
  ["elefante","Elefant","S(m)"],["mono","Affe","S(m)"],["serpiente","Schlange","S(f)"],
  ["araña","Spinne","S(f)"],["abeja","Biene","S(f)"],["mosca","Fliege","S(f)"],
  ["mariposa","Schmetterling","S(f)"],["hormiga","Ameise","S(f)"],["insecto","Insekt","S(m)"],
  ["águila","Adler","S(f)"],["paloma","Taube","S(f)"],["tortuga","Schildkröte","S(f)"],
  ["ballena","Wal","S(f)"],["tiburón","Hai","S(m)"],["delfín","Delfin","S(m)"],
  // ---- city & places ----
  ["ciudad","Stadt","S(f)"],["pueblo","Dorf","S(m)"],["barrio","Viertel","S(m)"],
  ["plaza","Platz","S(f)"],["avenida","Allee / Boulevard","S(f)"],["esquina","Ecke","S(f)"],
  ["acera","Gehweg","S(f)"],["semáforo","Ampel","S(m)"],["parque","Park","S(m)"],
  ["jardín","Garten","S(m)"],["museo","Museum","S(m)"],["teatro","Theater","S(m)"],
  ["cine","Kino","S(m)"],["biblioteca","Bibliothek","S(f)"],["universidad","Universität","S(f)"],
  ["colegio","Schule","S(m)"],["hospital","Krankenhaus","S(m)"],["banco","Bank / Sitzbank","S(m)"],
  ["correo","Post","S(m)"],["comisaría","Polizeiwache","S(f)"],["ayuntamiento","Rathaus","S(m)"],
  ["restaurante","Restaurant","S(m)"],["bar","Bar / Kneipe","S(m)"],["cafetería","Café","S(f)"],
  ["hotel","Hotel","S(m)"],["supermercado","Supermarkt","S(m)"],["panadería","Bäckerei","S(f)"],
  ["farmacia","Apotheke","S(f)"],["iglesia","Kirche","S(f)"],["catedral","Kathedrale","S(f)"],
  ["castillo","Burg / Schloss","S(m)"],["torre","Turm","S(f)"],["fábrica","Fabrik","S(f)"],
  ["aeropuerto","Flughafen","S(m)"],["estación","Bahnhof / Station","S(f)"],["puerto","Hafen","S(m)"],
  ["frontera","Grenze","S(f)"],["carretera","Landstraße","S(f)"],["autopista","Autobahn","S(f)"]
]);
