/* Frecuencia — deck expansion band C. Rows [es, de, pos]. Deduped at runtime. */
window.WORDS = (window.WORDS||[]).concat([
  // ---- transport & travel ----
  ["viaje","Reise","S(m)"],["coche","Auto","S(m)"],["autobús","Bus","S(m)"],
  ["metro","U-Bahn","S(m)"],["tranvía","Straßenbahn","S(m)"],["bicicleta","Fahrrad","S(f)"],
  ["moto","Motorrad","S(f)"],["camión","Lastwagen","S(m)"],["taxi","Taxi","S(m)"],
  ["barco","Schiff / Boot","S(m)"],["avión","Flugzeug","S(m)"],["tren","Zug","S(m)"],
  ["billete","Fahrkarte / Ticket","S(m)"],["boleto","Ticket","S(m)"],["asiento","Sitzplatz","S(m)"],
  ["maleta","Koffer","S(f)"],["equipaje","Gepäck","S(m)"],["pasaporte","Reisepass","S(m)"],
  ["aduana","Zoll","S(f)"],["vuelo","Flug","S(m)"],["destino","Ziel / Reiseziel","S(m)"],
  ["mapa","Karte (Land)","S(m)"],["ruta","Route","S(f)"],["viajero","Reisender","S(m)"],
  ["turista","Tourist","S(m)"],["gasolina","Benzin","S(f)"],["rueda","Rad / Reifen","S(f)"],
  ["motor","Motor","S(m)"],["volante","Lenkrad","S(m)"],["parada","Haltestelle","S(f)"],
  ["andén","Bahnsteig","S(m)"],["retraso","Verspätung","S(m)"],["horario","Fahrplan / Zeitplan","S(m)"],
  // ---- school, office, study ----
  ["clase","Unterricht / Klasse","S(f)"],["curso","Kurs","S(m)"],["examen","Prüfung","S(m)"],
  ["nota","Note / Notiz","S(f)"],["deberes","Hausaufgaben","S(m)"],["tarea","Aufgabe","S(f)"],
  ["ejercicio","Übung","S(m)"],["lección","Lektion","S(f)"],["asignatura","Schulfach","S(f)"],
  ["cuaderno","Heft","S(m)"],["libreta","Notizbuch","S(f)"],["lápiz","Bleistift","S(m)"],
  ["bolígrafo","Kugelschreiber","S(m)"],["goma","Radiergummi","S(f)"],["regla","Lineal / Regel","S(f)"],
  ["tijeras","Schere","S(f)"],["pegamento","Klebstoff","S(m)"],["pizarra","Tafel","S(f)"],
  ["mochila","Schulranzen","S(f)"],["diccionario","Wörterbuch","S(m)"],["página","Seite","S(f)"],
  ["capítulo","Kapitel","S(m)"],["título","Titel","S(m)"],["tema","Thema","S(m)"],
  ["resumen","Zusammenfassung","S(m)"],["apunte","Notiz / Mitschrift","S(m)"],["conocimiento","Wissen","S(m)"],
  ["carrera","Studium / Laufbahn","S(f)"],["beca","Stipendium","S(f)"],["oficina","Büro","S(f)"],
  ["reunión","Besprechung / Treffen","S(f)"],["proyecto","Projekt","S(m)"],["informe","Bericht","S(m)"],
  ["documento","Dokument","S(m)"],["contrato","Vertrag","S(m)"],["factura","Rechnung","S(f)"],
  ["sueldo","Gehalt","S(m)"],["salario","Lohn","S(m)"],["horario laboral","Arbeitszeit","S(m)"],
  ["vacaciones","Urlaub / Ferien","S(f)"],["negocio","Geschäft","S(m)"],["cargo","Posten / Amt","S(m)"],
  // ---- technology ----
  ["ordenador","Computer","S(m)"],["portátil","Laptop","S(m)"],["pantalla","Bildschirm","S(m)"],
  ["teclado","Tastatur","S(m)"],["ratón","Maus (Computer)","S(m)"],["móvil","Handy","S(m)"],
  ["teléfono","Telefon","S(m)"],["cámara","Kamera","S(f)"],["batería","Batterie / Akku","S(f)"],
  ["cargador","Ladegerät","S(m)"],["altavoz","Lautsprecher","S(m)"],["auricular","Kopfhörer","S(m)"],
  ["internet","Internet","S(m)"],["red","Netz / Netzwerk","S(f)"],["correo electrónico","E-Mail","S(m)"],
  ["mensaje","Nachricht","S(m)"],["archivo","Datei","S(m)"],["carpeta","Ordner","S(f)"],
  ["contraseña","Passwort","S(f)"],["usuario","Benutzer","S(m)"],["página web","Webseite","S(f)"],
  ["aplicación","App / Anwendung","S(f)"],["programa","Programm","S(m)"],["dato","Datum / Angabe","S(m)"],
  ["botón","Knopf / Schaltfläche","S(m)"],["señal","Signal","S(f)"],["conexión","Verbindung","S(f)"],
  ["pila","Batterie","S(f)"],["enchufar","einstecken / anschließen","V"],["descargar","herunterladen","V"],
  ["subir","hochladen","V"],["borrar","löschen","V"],["guardar","speichern","V"],
  ["conectar","verbinden","V"],["navegar","surfen / navigieren","V"],["teclear","tippen","V"],
  // ---- money, shopping, business ----
  ["dinero","Geld","S(m)"],["moneda","Münze / Währung","S(f)"],["billete","Geldschein","S(m)"],
  ["precio","Preis","S(m)"],["coste","Kosten","S(m)"],["gasto","Ausgabe","S(m)"],
  ["ahorro","Ersparnis","S(m)"],["deuda","Schuld","S(f)"],["préstamo","Kredit / Darlehen","S(m)"],
  ["ganancia","Gewinn","S(f)"],["pérdida","Verlust","S(f)"],["impuesto","Steuer","S(m)"],
  ["descuento","Rabatt","S(m)"],["oferta","Angebot","S(f)"],["rebaja","Preisnachlass","S(f)"],
  ["compra","Einkauf","S(f)"],["venta","Verkauf","S(f)"],["mercado","Markt","S(m)"],
  ["tienda","Geschäft / Laden","S(f)"],["caja","Kasse / Kiste","S(f)"],["recibo","Quittung","S(m)"],
  ["cuenta","Konto / Rechnung","S(f)"],["tarjeta","Karte","S(f)"],["efectivo","Bargeld","S(m)"],
  ["cambio","Wechselgeld / Wechsel","S(m)"],["bolsa","Tasche / Börse","S(f)"],["empresa","Firma","S(f)"],
  ["fábrica","Fabrik","S(f)"],["industria","Industrie","S(f)"],["comercio","Handel","S(m)"],
  ["economía","Wirtschaft","S(f)"],["riqueza","Reichtum","S(f)"],["pobreza","Armut","S(f)"],
  // ---- time expressions ----
  ["segundo","Sekunde","S(m)"],["minuto","Minute","S(m)"],["hora","Stunde","S(f)"],
  ["madrugada","frühe Morgenstunden","S(f)"],["amanecer","Morgengrauen","S(m)"],["mediodía","Mittag","S(m)"],
  ["atardecer","Abenddämmerung","S(m)"],["medianoche","Mitternacht","S(f)"],["semana","Woche","S(f)"],
  ["fin de semana","Wochenende","S(m)"],["mes","Monat","S(m)"],["año","Jahr","S(m)"],
  ["década","Jahrzehnt","S(f)"],["siglo","Jahrhundert","S(m)"],["época","Epoche / Zeit","S(f)"],
  ["momento","Moment","S(m)"],["rato","Weile","S(m)"],["instante","Augenblick","S(m)"],
  ["martes","Dienstag","S(m)"],["miércoles","Mittwoch","S(m)"],["jueves","Donnerstag","S(m)"],
  ["sábado","Samstag","S(m)"],["domingo","Sonntag","S(m)"],["enero","Januar","S(m)"],
  ["febrero","Februar","S(m)"],["marzo","März","S(m)"],["abril","April","S(m)"],
  ["mayo","Mai","S(m)"],["junio","Juni","S(m)"],["julio","Juli","S(m)"],
  ["agosto","August","S(m)"],["septiembre","September","S(m)"],["octubre","Oktober","S(m)"],
  ["noviembre","November","S(m)"],["diciembre","Dezember","S(m)"],["primavera","Frühling","S(f)"],
  ["verano","Sommer","S(m)"],["otoño","Herbst","S(m)"],["invierno","Winter","S(m)"],
  ["cumpleaños","Geburtstag","S(m)"],["fecha","Datum","S(f)"],["calendario","Kalender","S(m)"],
  ["pasado","Vergangenheit / vergangen","S(m)"],["presente","Gegenwart","S(m)"],["futuro","Zukunft","S(m)"],
  ["anoche","gestern Abend","Adv"],["anteayer","vorgestern","Adv"],["pasado mañana","übermorgen","Adv"],
  ["actualmente","derzeit / momentan","Adv"],["recientemente","kürzlich","Adv"],["antiguamente","früher / einst","Adv"],
  // ---- feelings & character (adjectives) ----
  ["amable","freundlich / nett","Adj"],["simpático","sympathisch","Adj"],["antipático","unsympathisch","Adj"],
  ["gracioso","witzig","Adj"],["serio","ernst","Adj"],["tímido","schüchtern","Adj"],
  ["valiente","mutig","Adj"],["cobarde","feige","Adj"],["orgulloso","stolz","Adj"],
  ["celoso","eifersüchtig","Adj"],["generoso","großzügig","Adj"],["egoísta","egoistisch","Adj"],
  ["honesto","ehrlich","Adj"],["sincero","aufrichtig","Adj"],["mentiroso","verlogen","Adj"],
  ["educado","höflich","Adj"],["grosero","unhöflich / grob","Adj"],["paciente","geduldig","Adj"],
  ["nervioso","nervös","Adj"],["tranquilo","ruhig","Adj"],["inteligente","intelligent","Adj"],
  ["listo","clever / fertig","Adj"],["tonto","dumm","Adj"],["trabajador","fleißig","Adj"],
  ["perezoso","faul","Adj"],["responsable","verantwortungsvoll","Adj"],["torpe","ungeschickt","Adj"],
  ["amistoso","freundschaftlich","Adj"],["cariñoso","liebevoll / zärtlich","Adj"],["sensible","sensibel","Adj"],
  ["enfadado","verärgert","Adj"],["asustado","verängstigt","Adj"],["sorprendido","überrascht","Adj"],
  ["preocupado","besorgt","Adj"],["aburrido","gelangweilt / langweilig","Adj"],["emocionado","aufgeregt / gerührt","Adj"],
  ["orgullo","Stolz","S(m)"],["vergüenza","Scham / Peinlichkeit","S(f)"],["celos","Eifersucht","S(m)"],
  ["esperanza","Hoffnung","S(f)"],["confianza","Vertrauen","S(f)"],["ánimo","Mut / Laune","S(m)"],
  ["cariño","Zuneigung","S(m)"],["odio","Hass","S(m)"],["envidia","Neid","S(f)"],
  // ---- more everyday adjectives ----
  ["duro","hart","Adj"],["blando","weich","Adj"],["suave","sanft / weich","Adj"],
  ["áspero","rau","Adj"],["pesado","schwer / lästig","Adj"],["ligero","leicht","Adj"],
  ["grueso","dick","Adj"],["delgado","dünn / schlank","Adj"],["gordo","dick / fett","Adj"],
  ["profundo","tief","Adj"],["estrecho","eng / schmal","Adj"],["amplio","weit / geräumig","Adj"],
  ["redondo","rund","Adj"],["cuadrado","quadratisch","Adj"],["recto","gerade","Adj"],
  ["torcido","krumm / schief","Adj"],["seco","trocken","Adj"],["mojado","nass","Adj"],
  ["húmedo","feucht","Adj"],["fresco","frisch / kühl","Adj"],["templado","mild / lauwarm","Adj"],
  ["moderno","modern","Adj"],["antiguo","alt / antik","Adj"],["actual","aktuell","Adj"],
  ["común","gewöhnlich / gemeinsam","Adj"],["raro","selten / seltsam","Adj"],["extraño","fremd / seltsam","Adj"],
  ["normal","normal","Adj"],["especial","besonders","Adj"],["perfecto","perfekt","Adj"],
  ["completo","vollständig","Adj"],["entero","ganz","Adj"],["medio","halb","Adj"],
  ["único","einzig / einzigartig","Adj"],["principal","haupt- / wichtigste","Adj"],["general","allgemein","Adj"],
  ["privado","privat","Adj"],["público","öffentlich","Adj"],["famoso","berühmt","Adj"],
  ["conocido","bekannt","Adj"],["desconocido","unbekannt","Adj"],["verdadero","wahr / echt","Adj"],
  ["justo","gerecht / genau","Adj"],["injusto","ungerecht","Adj"],["seguro","sicher","Adj"],
  ["peligroso","gefährlich","Adj"],["útil","nützlich","Adj"],["inútil","nutzlos","Adj"],
  ["sencillo","einfach / schlicht","Adj"],["complicado","kompliziert","Adj"],["claro","klar / hell","Adj"],
  ["evidente","offensichtlich","Adj"],["posible","möglich","Adj"],["imposible","unmöglich","Adj"],
  ["cierto","gewiss / wahr","Adj"],["dudoso","zweifelhaft","Adj"],["suficiente","ausreichend","Adj"],
  ["escaso","knapp / spärlich","Adj"],["numeroso","zahlreich","Adj"],["frecuente","häufig","Adj"],
  // ---- numbers ----
  ["cero","null","Num"],["once","elf","Num"],["doce","zwölf","Num"],
  ["trece","dreizehn","Num"],["catorce","vierzehn","Num"],["quince","fünfzehn","Num"],
  ["dieciséis","sechzehn","Num"],["diecisiete","siebzehn","Num"],["dieciocho","achtzehn","Num"],
  ["diecinueve","neunzehn","Num"],["veinte","zwanzig","Num"],["treinta","dreißig","Num"],
  ["cuarenta","vierzig","Num"],["cincuenta","fünfzig","Num"],["sesenta","sechzig","Num"],
  ["setenta","siebzig","Num"],["ochenta","achtzig","Num"],["noventa","neunzig","Num"],
  ["doscientos","zweihundert","Num"],["quinientos","fünfhundert","Num"],["millón","Million","Num"],
  ["tercero","dritte(r)","Num"],["cuarto","vierte(r) / Viertel","Num"],["quinto","fünfte(r)","Num"],
  ["mitad","Hälfte","S(f)"],["docena","Dutzend","S(f)"],["par","Paar","S(m)"],
  // ---- adverbs & connectors ----
  ["quizás","vielleicht","Adv"],["seguramente","sicherlich","Adv"],["probablemente","wahrscheinlich","Adv"],
  ["afortunadamente","glücklicherweise","Adv"],["desgraciadamente","leider","Adv"],["finalmente","schließlich","Adv"],
  ["generalmente","im Allgemeinen","Adv"],["normalmente","normalerweise","Adv"],["especialmente","besonders","Adv"],
  ["exactamente","genau","Adv"],["completamente","völlig","Adv"],["absolutamente","absolut","Adv"],
  ["totalmente","total / gänzlich","Adv"],["apenas","kaum","Adv"],["incluso","sogar","Adv"],
  ["sobre todo","vor allem","Adv"],["al menos","wenigstens","Adv"],["a lo mejor","vielleicht","Adv"],
  ["de nuevo","erneut","Adv"],["otra vez","noch einmal","Adv"],["en cambio","dagegen / hingegen","Adv"],
  ["por lo tanto","daher / folglich","Adv"],["así que","also / deshalb","Konj"],["de modo que","sodass","Konj"],
  ["a pesar de","trotz","Präp"],["gracias a","dank","Präp"],["a causa de","wegen","Präp"],
  ["en lugar de","anstatt","Präp"],["además de","außer / zusätzlich zu","Präp"],["junto a","neben","Präp"],
  ["alrededor de","um … herum / ungefähr","Präp"],["a través de","durch / mittels","Präp"],["en vez de","statt","Präp"],
  ["mientras tanto","inzwischen","Adv"],["por cierto","übrigens","Adv"],["en realidad","in Wirklichkeit","Adv"],
  ["de hecho","tatsächlich","Adv"],["en general","im Allgemeinen","Adv"],["por lo general","normalerweise","Adv"],
  ["cada vez","jedes Mal","Adv"],["a veces","manchmal","Adv"],["de vez en cuando","ab und zu","Adv"],
  ["en cuanto","sobald","Konj"],["tan pronto como","sobald","Konj"],["siempre que","immer wenn / sofern","Konj"],
  ["a menos que","es sei denn","Konj"],["con tal de que","sofern","Konj"],["para que","damit","Konj"]
]);
